### ISSUE TITLE
Carts floor texture has wrong rotation  

### ISSUE THREAD

**Issue by lightonflux** [SummerFields/Minetest#10]
I think the floor has to be rotated at 90° to be correct.

Video: http://videobin.org/+8my/bi3.ogg

**Comment by lipki** [comment]
he is wrong on top, but he is right on bottom.

**Comment by lightonflux** [comment]
That is weird. Is that a problem with the engine?

**Comment by lipki** [comment]
This is the model of the mod, it's not very serious.
