### ISSUE TITLE
Wood texture always cracky

### ISSUE THREAD

**Issue by lightonflux** [SummerFields/Minetest#12]
Wood even when in a tree is always cracky, as if dried out. This makes it a bit unrealistic and makes wood floors look a bit broken. A more natural appearance would make floors and tree look more healthy
![default_tree_top](https://cloud.githubusercontent.com/assets/1377943/11046687/17a2f85a-872f-11e5-8874-458252e3be0a.png)

**Comment by lipki** [comment]
Yes but no.
