### ISSUE TITLE
Mod support for X decor

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Minetest#13]
@lipki Mod support for X decor. this is one of my favorite Minetest mods and it's pretty popular so that's why i request this. ([link to the mod](https://forum.minetest.net/viewtopic.php?t=12534))

**Comment by lipki** [comment]
It's work! So I make mod when I have time.
And especially when I play with, and I do not play with Minetest. :-\

**Comment by tobyplowy** [comment]
@lipki is it good if I port the Mod?

**Comment by lipki** [comment]
oh yes :D

**Comment by tobyplowy** [comment]
@lipki did you already work on this. (Is there any textures you already made?) so I don't have to do extra work :sweat_smile:

**Comment by tobyplowy** [comment]
@lipki i already have some textures (for the mod) done what do you think 

original textures 
![chess_bg](https://cloud.githubusercontent.com/assets/16853304/15686760/0b63bd3e-2772-11e6-91fa-2b92574b8721.png)
![chessboard_top](https://cloud.githubusercontent.com/assets/16853304/15686766/0e406426-2772-11e6-85a9-e89bc0c54da3.png)
![chessboard_sides](https://cloud.githubusercontent.com/assets/16853304/15686767/1038c4bc-2772-11e6-9441-9d43124759fa.png)
![xdecor_mailbox_bottom](https://cloud.githubusercontent.com/assets/16853304/15686774/17a0297a-2772-11e6-97e8-d0af8ca0f65b.png)
![xdecor_mailbox_side](https://cloud.githubusercontent.com/assets/16853304/15686781/1c582d5a-2772-11e6-9b79-651c140e1d6c.png)
![xdecor_mailbox_top](https://cloud.githubusercontent.com/assets/16853304/15686784/1e30dfb4-2772-11e6-93f5-0c1ea73963ba.png)
![xdecor_mailbox](https://cloud.githubusercontent.com/assets/16853304/15686785/206a4ae0-2772-11e6-8899-0ad6388a5ff1.png)

my textures 

![xdecor_mailbox](https://cloud.githubusercontent.com/assets/16853304/15686804/29692008-2772-11e6-9907-48c74d4f24db.png)
![xdecor_mailbox_bottom](https://cloud.githubusercontent.com/assets/16853304/15686810/2c299c1e-2772-11e6-97ff-859bc7b57b53.png)
![xdecor_mailbox_side](https://cloud.githubusercontent.com/assets/16853304/15686813/2dfa58f8-2772-11e6-916b-5e6716d1c5ed.png)
![xdecor_mailbox_top](https://cloud.githubusercontent.com/assets/16853304/15686817/2ff6e388-2772-11e6-9ea1-8cff0e3ef2e2.png)
![chess_bg](https://cloud.githubusercontent.com/assets/16853304/15686823/35d34d96-2772-11e6-94b9-3bd643a5c9fa.png)
![chessboard_top](https://cloud.githubusercontent.com/assets/16853304/15686827/3873271a-2772-11e6-9415-fd796ec8623c.png)

**Comment by tobyplowy** [comment]
@lipki bdw if you want to do some stuff here ar som textures 

cactusbrick
![xdecor_cactusbrick](https://cloud.githubusercontent.com/assets/16853304/15686898/7b93674e-2772-11e6-9d8e-9ea69718ed16.png)

shess peases

![bishop_black](https://cloud.githubusercontent.com/assets/16853304/15687032/017cbbf8-2773-11e6-8350-96f98e5f81f5.png)
![bishop_white](https://cloud.githubusercontent.com/assets/16853304/15687034/0417c592-2773-11e6-89d1-236a593fc7bf.png)
![king_black](https://cloud.githubusercontent.com/assets/16853304/15686914/8a9c4b84-2772-11e6-83bf-7989e0b43fdf.png)
![king_white](https://cloud.githubusercontent.com/assets/16853304/15686919/8d91cc2e-2772-11e6-861d-1f9002de6b5b.png)
![knight_black](https://cloud.githubusercontent.com/assets/16853304/15686920/8ffe2eda-2772-11e6-8cec-8724b6ebd9cd.png)
![knight_white](https://cloud.githubusercontent.com/assets/16853304/15686921/92022a6a-2772-11e6-9273-00f5947dd517.png)
![pawn_black](https://cloud.githubusercontent.com/assets/16853304/15686930/98bd2206-2772-11e6-9eca-66b65a12e0a9.png)
![pawn_white](https://cloud.githubusercontent.com/assets/16853304/15686932/9a35c4a8-2772-11e6-82bd-7cd3357bdfbd.png)
![queen_black](https://cloud.githubusercontent.com/assets/16853304/15686937/9bbecbe4-2772-11e6-9b01-afe7db7705e5.png)
![queen_white](https://cloud.githubusercontent.com/assets/16853304/15686939/9cfa8e8a-2772-11e6-98d7-03eb70230209.png)
![rook_black](https://cloud.githubusercontent.com/assets/16853304/15686942/a08dc0ee-2772-11e6-94cf-1baaa5f07164.png)
![rook_white](https://cloud.githubusercontent.com/assets/16853304/15686946/a3be6c78-2772-11e6-96fa-96b681830de9.png)

bee

![hive_bee](https://cloud.githubusercontent.com/assets/16853304/15686956/afc28676-2772-11e6-98f7-52874718ec34.png)

bee hive
![hive_layout](https://cloud.githubusercontent.com/assets/16853304/15686965/b6dee238-2772-11e6-8bfb-55740f458546.png)

bee howse thing (i guess)
![xdecor_hive_front](https://cloud.githubusercontent.com/assets/16853304/15687016/f0b67c64-2772-11e6-8d91-69a41132e065.png)
![xdecor_hive_side](https://cloud.githubusercontent.com/assets/16853304/15687018/f2871b66-2772-11e6-93bf-28fa2324909e.png)
![xdecor_hive_top](https://cloud.githubusercontent.com/assets/16853304/15687019/f41716d4-2772-11e6-9cd9-a00f72b7c4f5.png)

lantern

![xdecor_lantern](https://cloud.githubusercontent.com/assets/16853304/15687084/305ef9fe-2773-11e6-881a-c36b9c0e0835.png)
![xdecor_lantern_inv](https://cloud.githubusercontent.com/assets/16853304/15687086/3445647c-2773-11e6-8ea4-dc77b87e0794.png)

candle

![xdecor_candle_inv](https://cloud.githubusercontent.com/assets/16853304/15687094/44a1aa24-2773-11e6-83a8-22bbfc7af1c6.png)
![xdecor_candle_wall](https://cloud.githubusercontent.com/assets/16853304/15687099/4b2ae8f6-2773-11e6-9ab4-bef19fb14043.png)
![xdecor_candle_wield](https://cloud.githubusercontent.com/assets/16853304/15687106/4d8532dc-2773-11e6-8522-d21c73d8362e.png)

otther

![worktable_saw](https://cloud.githubusercontent.com/assets/16853304/15687118/5a3a73b6-2773-11e6-83c9-50105303fdd3.png)
 
open book

![xdecor_book_open](https://cloud.githubusercontent.com/assets/16853304/15687127/67241e7e-2773-11e6-9e17-889e0cebc434.png)

all the rest is my work ;D

**Comment by lipki** [comment]
You used the cake to the chessboard block.
But you did not keep the colors for the big chessboard.
In addition the black and white is wrong.
https://github.com/SummerFields/SummerFields/wiki/Texture-Making-Resources

But the mailbox is awesome.

**Comment by lipki** [comment]
![worktable_saw](https://cloud.githubusercontent.com/assets/401965/15689810/fa1a844a-2780-11e6-883b-5b01cc047376.png)  ![worktable_saw](https://cloud.githubusercontent.com/assets/401965/15689502/85c59c34-277f-11e6-88ec-e782a751f322.png)
![hammer_layout](https://cloud.githubusercontent.com/assets/401965/15689820/093a7372-2781-11e6-96c9-38ae5b212c31.png)   ![hammer_layout](https://cloud.githubusercontent.com/assets/401965/15689615/189699d2-2780-11e6-8b77-cf2777a5e66c.png)
![xdecor_hammer](https://cloud.githubusercontent.com/assets/401965/15689867/271dd1ea-2781-11e6-8ea1-6a81bca46ac1.png)  ![xdecor_hammer](https://cloud.githubusercontent.com/assets/401965/15689553/d634e6ac-277f-11e6-8d12-2d8b1d66f46b.png)
![xdecor_bowl](https://cloud.githubusercontent.com/assets/401965/15689883/37820b1e-2781-11e6-95c9-a277c181ca5b.png)   ![xdecor_bowl](https://cloud.githubusercontent.com/assets/401965/15689781/dec515d4-2780-11e6-896c-92f4c57406b4.png)
![xdecor_bowl_soup](https://cloud.githubusercontent.com/assets/401965/15689911/5f4012c2-2781-11e6-8b5c-ae11d578e216.png)![mushroom_stew](https://cloud.githubusercontent.com/assets/401965/15689956/885531b0-2781-11e6-8362-1511314f1c93.png)

**Comment by lipki** [comment]
![xdecor_book_open](https://cloud.githubusercontent.com/assets/401965/15690002/b7c5e9ee-2781-11e6-8b84-4f6c7c124f2b.png)![xdecor_book_open](https://cloud.githubusercontent.com/assets/401965/15691108/44a64480-2787-11e6-929c-410791bf7a9f.png)

**Comment by tobyplowy** [comment]
@lipki nice textures

**Comment by tobyplowy** [comment]
@lipki i fixed the color on the shess bord
![chessboard_top](https://cloud.githubusercontent.com/assets/16853304/15705063/c317d58e-27ed-11e6-8292-c668651a4b4b.png)

**Comment by tobyplowy** [comment]
@lipki xdecor_cactusbrick done
![xdecor_cactusbrick](https://cloud.githubusercontent.com/assets/16853304/15705764/e750dc54-27f0-11e6-9694-888981c0af3b.png)
i did my best

**Comment by tobyplowy** [comment]
@lipki xdecor wood is done 
![xdecor_wood](https://cloud.githubusercontent.com/assets/16853304/15709219/d20931da-2803-11e6-889e-23e4bad29f29.png)
![xdecor_wood_tile](https://cloud.githubusercontent.com/assets/16853304/15709220/d32cb7bc-2803-11e6-9c2f-8798b004a5ee.png)

I have to remove the things at the side of the wood otherwise The furniture didn't Look good

**Comment by tobyplowy** [comment]
@lipki i made the asian type Window
![xdecor_wood_frame](https://cloud.githubusercontent.com/assets/16853304/15711098/ef4ef6b8-280c-11e6-9715-4feab3258fa5.png)

**Comment by tobyplowy** [comment]
@lipki what do you think about the stuff i made?

**Comment by lipki** [comment]
so !

This is the chess_bg you should sing to remove the black.
Black is poo.
But the use of quartz is good.

For cactus I propose an alternative.
left you, right me.
![xdecor_cactusbrick](https://cloud.githubusercontent.com/assets/16853304/15705764/e750dc54-27f0-11e6-9694-888981c0af3b.png)![xdecor_cactusbrick](https://cloud.githubusercontent.com/assets/401965/15725305/8f187ce4-284b-11e6-8b75-4ac50ffd33f2.png)![cactus](https://cloud.githubusercontent.com/assets/401965/15723957/1eb6c506-2845-11e6-96e8-7c9072bbfb09.png)
What do you think ?

For tile wood, I do not like;) I also did one.
![xdecor_wood_tile](https://cloud.githubusercontent.com/assets/16853304/15709220/d32cb7bc-2803-11e6-9c2f-8798b004a5ee.png)![xdecor_wood_tile](https://cloud.githubusercontent.com/assets/401965/15725300/8b315ed4-284b-11e6-8763-e1ab63225baf.png)
![xdecor_wood_tile](https://cloud.githubusercontent.com/assets/401965/15725398/f5d82092-284b-11e6-909d-a9d26d4138d2.png)

The windows is great !

**Comment by tobyplowy** [comment]
@lipki man I'm so bad at this‚ you are so good :cry: (my texturs look like shit in comparison to you)

**Comment by lipki** [comment]
I'm doing this for years, I'm used to.
Do not worry you're doing well.

**Comment by tobyplowy** [comment]
@lipki could you please do the Chess Pieces, i have no Idea how i culd do it. 

bishop
![bishop_black](https://cloud.githubusercontent.com/assets/16853304/15746110/67a14c92-28d5-11e6-97da-6c8391d14874.png)
![bishop_white](https://cloud.githubusercontent.com/assets/16853304/15746115/6c7b7896-28d5-11e6-9347-840b27e4e5d3.png)

king
![king_black](https://cloud.githubusercontent.com/assets/16853304/15746122/79924104-28d5-11e6-854b-4d03324fe262.png)
![king_white](https://cloud.githubusercontent.com/assets/16853304/15746127/7fbe60f8-28d5-11e6-9978-c0bb555f43a6.png)

knight 

![knight_black](https://cloud.githubusercontent.com/assets/16853304/15746138/8f18c0d4-28d5-11e6-8a15-2b940ab3a5d8.png)
![knight_white](https://cloud.githubusercontent.com/assets/16853304/15746141/90f2dc0a-28d5-11e6-95f9-2222aafcbaba.png)

pawn
![pawn_black](https://cloud.githubusercontent.com/assets/16853304/15746160/a17f5846-28d5-11e6-9777-9c5d5cbd3913.png)
![pawn_white](https://cloud.githubusercontent.com/assets/16853304/15746163/a3b05214-28d5-11e6-9a7f-cf509950934a.png)

queen
![queen_black](https://cloud.githubusercontent.com/assets/16853304/15746172/acb3c86e-28d5-11e6-8afa-a87e1c11b9e1.png)
![queen_white](https://cloud.githubusercontent.com/assets/16853304/15746174/aec2045e-28d5-11e6-9287-114211cbe05e.png)

rook
![rook_black](https://cloud.githubusercontent.com/assets/16853304/15746181/b3147a78-28d5-11e6-89d6-c974c6cbe8e4.png)
![rook_white](https://cloud.githubusercontent.com/assets/16853304/15746182/b4904102-28d5-11e6-9b1d-86d736f4faa0.png)

**Comment by tobyplowy** [comment]
@lipki I have re colored my Texture To Look More like Yours. My Texture shuld be used as a custom texture for the people that don't like the pointy Bits that hurt you ;P

**Comment by tobyplowy** [comment]
@lipki I have re colored my Texture To Look More like Yours. My Texture shuld be used as a custom texture for the people that don't like the pointy Bits that hurt you ;P

![xdecor_cactusbrick](https://cloud.githubusercontent.com/assets/16853304/15746667/cd04456a-28d7-11e6-8538-e09b1317e98b.png)
![8f187ce4-284b-11e6-8b75-4ac50ffd33f2](https://cloud.githubusercontent.com/assets/16853304/15746661/c826bd20-28d7-11e6-88f5-34ce409eb198.png)
the top one is my new texture.

**Comment by lipki** [comment]
https://www.youtube.com/watch?v=E05SSymMvdY
:D

**Comment by tobyplowy** [comment]
@lipki lol that video was random :D

**Comment by lipki** [comment]
for the chess pieces ..
for minecraft I would have a small mob.
But for Minetest I have no good idea.

**Comment by tobyplowy** [comment]
@lipki it's for x decor ( you know the Mod for minetest)

**Comment by lipki** [comment]
![rook_black](https://cloud.githubusercontent.com/assets/401965/15755759/89ab0b1a-28fe-11e6-9e31-af2635a46f23.png)![rook_white](https://cloud.githubusercontent.com/assets/401965/15755760/89ae6d28-28fe-11e6-8f5c-bf4faaa6d1fa.png)

one test

**Comment by lipki** [comment]
Well, I make you a repo, you know use git?

**Comment by tobyplowy** [comment]
No i downt know how to use git sorry

**Comment by tobyplowy** [comment]
@lipki I know you have to do something called branching but I have no idea what it is :P im a noob :(

**Comment by tobyplowy** [comment]
@lipki is the test you made the rook? Or a Bishop?

**Comment by lipki** [comment]
rook
Ok, I'll update the repo.
Anyway you can make issue here.
https://github.com/SummerFields/Mod-Mintest-xDecor

**Comment by tobyplowy** [comment]
Can this issue Be closer?  Because Its moved to [this page](https://github.com/SummerFields/Mod-Mintest-xDecor)
