### ISSUE TITLE
original ore's 

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Minetest#14]
@lipki The minetest port of the texture pack uses other ore's i really don't like this I like the original ore's 
Maybe the Minetest pack could get the new original ores

**Comment by lipki** [comment]
I do not like the original ore ...
I do not like those of Minetest either, but it is a bit more readable.
Proposed the change, we'll see.

**Comment by tobyplowy** [comment]
@lipki so what will we do

**Comment by tobyplowy** [comment]
@lipki close?

**Comment by lipki** [comment]
No, the issue is not settled.
Let's leave it for now.

**Comment by lipki** [comment]
Well, we'll try that.

**Comment by lipki** [comment]
![default_mineral_coal](https://cloud.githubusercontent.com/assets/401965/22254746/c7150116-e255-11e6-8f9e-9bbbaaa2b700.png)![default_mineral_copper](https://cloud.githubusercontent.com/assets/401965/22254748/c71deec0-e255-11e6-9f1b-5902e75d2d96.png)![default_mineral_diamond](https://cloud.githubusercontent.com/assets/401965/22254747/c71b88ec-e255-11e6-8ab6-2357f2aa46d8.png)![default_mineral_gold](https://cloud.githubusercontent.com/assets/401965/22254749/c71e25f2-e255-11e6-91ff-a1dc8d0f5bbd.png)![default_mineral_iron](https://cloud.githubusercontent.com/assets/401965/22254751/c7224e7a-e255-11e6-95c7-5003ae76bf26.png)![default_mineral_mese](https://cloud.githubusercontent.com/assets/401965/22254752/c729acba-e255-11e6-91f7-bbf994763d06.png)

![default_mineral_coal](https://cloud.githubusercontent.com/assets/401965/22254791/defb4c0e-e255-11e6-99bb-3085e74d798e.png)![default_mineral_copper](https://cloud.githubusercontent.com/assets/401965/22254792/deff6e06-e255-11e6-8ec2-4dbc32b094aa.png)![default_mineral_diamond](https://cloud.githubusercontent.com/assets/401965/22254793/df00e4f2-e255-11e6-8931-0adb321fc4e3.png)![default_mineral_gold](https://cloud.githubusercontent.com/assets/401965/22254794/df041ab4-e255-11e6-922f-19e220a7a9d8.png)![default_mineral_iron](https://cloud.githubusercontent.com/assets/401965/22254796/df0bf3c4-e255-11e6-9c1a-ac82e6b7a15c.png)![default_mineral_mese](https://cloud.githubusercontent.com/assets/401965/22254795/df0966a4-e255-11e6-8a8e-a11499642719.png)

![coal_ore](https://cloud.githubusercontent.com/assets/401965/22254878/1192aa68-e256-11e6-88a9-ecb9cff97236.png)![blockorecopper](https://cloud.githubusercontent.com/assets/401965/22254942/4079c0aa-e256-11e6-9562-68011d58db2b.png)![default_mineral_diamond](https://cloud.githubusercontent.com/assets/401965/22254793/df00e4f2-e255-11e6-8931-0adb321fc4e3.png)![gold_ore](https://cloud.githubusercontent.com/assets/401965/22255089/9bd0870e-e256-11e6-8596-ac8e32e23f31.png)![iron_ore](https://cloud.githubusercontent.com/assets/401965/22255099/aa27aa08-e256-11e6-9e12-e81c4e51a7aa.png)![default_mineral_mese](https://cloud.githubusercontent.com/assets/401965/22254795/df0966a4-e255-11e6-8a8e-a11499642719.png)

![default_coal_lump](https://cloud.githubusercontent.com/assets/401965/22255132/d0baef5e-e256-11e6-9ea2-298b6f710625.png)![default_copper_lump](https://cloud.githubusercontent.com/assets/401965/22255144/d8ecf582-e256-11e6-9a79-d617ccbfe94e.png)![default_diamond](https://cloud.githubusercontent.com/assets/401965/22255202/e525cd60-e256-11e6-8923-9d8baeb261b6.png)![default_gold_lump](https://cloud.githubusercontent.com/assets/401965/22255210/f11786a4-e256-11e6-9df2-aa5616766115.png)![default_iron_lump](https://cloud.githubusercontent.com/assets/401965/22255221/faa118c0-e256-11e6-8b59-6da8ca4f7a43.png)![default_mese_crystal](https://cloud.githubusercontent.com/assets/401965/22255232/0429b6f4-e257-11e6-8ce4-4402ce4906be.png)

**Comment by lipki** [comment]
![capture du 2017-01-24 17-21-07](https://cloud.githubusercontent.com/assets/401965/22257050/0a316d3e-e25d-11e6-92d1-c81f496f51f8.png)
Like that, it's better ?

**Comment by tobyplowy** [comment]
@lipki yeh that's good
