### ISSUE TITLE
better glass doors

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Minetest#16]
![doors_door_obsidian_glass](https://cloud.githubusercontent.com/assets/16853304/20041482/f37096d2-a469-11e6-8a3a-857f80bff136.png)
![doors_door_glass](https://cloud.githubusercontent.com/assets/16853304/20041483/f3848340-a469-11e6-88da-65a0c4d5eb33.png)

**Comment by lipki** [comment]
move to #48
