### ISSUE TITLE
new update

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Minetest#17]
default_book_slot
![default_book_slot](https://cloud.githubusercontent.com/assets/16853304/20041537/fc204d4e-a46a-11e6-82c2-659919efb27e.png)
vessels_glass_bottle_slot
![vessels_glass_bottle_slot](https://cloud.githubusercontent.com/assets/16853304/20041552/433e2764-a46b-11e6-9a5e-00b4fb1e4cc0.png)

**Comment by tobyplowy** [comment]
new wood closer to original minetest wood
default_acacia_wood
![default_acacia_wood](https://cloud.githubusercontent.com/assets/16853304/20282218/2aa8e712-aab4-11e6-9d32-71bfcb19b2cc.png)
default_aspen_wood
![default_aspen_wood](https://cloud.githubusercontent.com/assets/16853304/20282219/2ac20dd2-aab4-11e6-80ec-3db7b1b41aca.png)
default_junglewood
![default_junglewood](https://cloud.githubusercontent.com/assets/16853304/20282221/2ac8b6c8-aab4-11e6-8f7a-ba938cfe1454.png)
default_pine_wood
![default_pine_wood](https://cloud.githubusercontent.com/assets/16853304/20282220/2ac6d83a-aab4-11e6-94b1-fb7852213a32.png)

**Comment by tobyplowy** [comment]
default_sandstone_block
![default_sandstone_block](https://cloud.githubusercontent.com/assets/16853304/20282302/7cb4e63c-aab4-11e6-94be-2c3bf79e7cea.png)

**Comment by tobyplowy** [comment]
default_silver_sand
![default_silver_sand](https://cloud.githubusercontent.com/assets/16853304/20282312/873d85b4-aab4-11e6-9ba5-8075c084cec7.png)

**Comment by tobyplowy** [comment]
new nyancat_rainbow added antialiasing
![nyancat_rainbow](https://cloud.githubusercontent.com/assets/16853304/20282496/363b853e-aab5-11e6-9655-163351babb65.png)

**Comment by tobyplowy** [comment]
maby a new farming_straw
![farming_straw](https://cloud.githubusercontent.com/assets/16853304/20282963/4ef7f25e-aab7-11e6-8da4-3860b17049ad.png)

**Comment by lipki** [comment]
I do not find these two textures ?
default_book_slot
vessels_glass_bottle_slot

**Comment by tobyplowy** [comment]
@lipki download this its the latest unstable build https://github.com/minetest/minetest_game then go to minetest_game-master\mods\default\default_book_slot.png or C:\Games\Minetest unstable\games\minetest_game-master\mods\vessels\textures\vessels_glass_bottle_slot.png
also this is were you can finde the coral textures

vessels_glass_bottle_slot
