### ISSUE TITLE
add sun and moon png

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Minetest#18]
bace minetest sun and moon 
![moon](https://cloud.githubusercontent.com/assets/16853304/20247328/b7d7d210-a9c9-11e6-911e-f2ccbc9fd0d7.png)
![sun](https://cloud.githubusercontent.com/assets/16853304/20247329/b7d88a84-a9c9-11e6-906b-125689ba580e.png)

@lipki i cant get rid of the black on the sun and moon in summerfealds anny ideas?

**Comment by lipki** [comment]
like this ?
![sun](https://cloud.githubusercontent.com/assets/401965/20275107/8af0d390-aa97-11e6-90a8-2e438d338eaa.png) <- the sun is here
![moon_phases](https://cloud.githubusercontent.com/assets/401965/20275213/f90caa2a-aa97-11e6-8a29-925bdf001cca.png)

**Comment by tobyplowy** [comment]
@lipki yeah exactly like that is the glow still there I can't tell with the white background also Are You Back or will you be offline Again

**Comment by tobyplowy** [comment]
@lipki you need to use the images i provided as resolution base (I think you can upscale them) The Moon has Only One frame also their name should be moon.png and sun.png

**Comment by lipki** [comment]
I'm back, for the moment.
I fix all the "issues" on hold, and I do the realease 1.11.

**Comment by tobyplowy** [comment]
I'm happy your back :D

Can you make issues for the new textures That are coming to the new update of minetest  The new update is not released yet (It's coming Pretty soon) so i already want to work on the textures thers new stuff like corals Yes corals :)
https://github.com/minetest/minetest_game

**Comment by lipki** [comment]
You can do it if you want, I put you in charge of minetest.
If you want you can even make the releases.
I immediately release the 1.11, and I made the spell of work in progress.
Then I would look for minetest.

**Comment by lipki** [comment]
But you make me want to test the new version: D

**Comment by tobyplowy** [comment]
@lipki You schuld definitely play The new update its awesome :)

**Comment by tobyplowy** [comment]
@lipki
sun.png
![sun](https://cloud.githubusercontent.com/assets/16853304/20323489/4143a092-ab7d-11e6-9c57-8b07b7295d30.png)
moon.png
![moon](https://cloud.githubusercontent.com/assets/16853304/20323490/41587134-ab7d-11e6-829f-460599ffd6f2.png)
you can add these to the minetest pack

**Comment by tobyplowy** [comment]
@lipki will you update the minetest pack I will help of course.

**Comment by lipki** [comment]
I do not find this two textures.

**Comment by tobyplowy** [comment]
@lipki yes they are not in the base texture folder but you can just put it in the texture pack folder and it will overwrite the Sun and Moon textures (I don't know why they didn't add the files probably to save memory or whatever XD)

**Comment by lipki** [comment]
ok

**Comment by lipki** [comment]
https://github.com/SummerFields/Minetest/commit/fd328d1b5a743ae97733be6d07052baf48d16ecd
