### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#19]
I make the releases when I can.

I have not yet managed to run the latest version of minetest.
And billions of mod, boring me a lot.

**Comment by lipki** [comment]
English bottom
@tobyplowy, j'espère que tu n'as pas mal pris ma remarque.
Avec l'écrit en plus de la traduction approximative, il est difficile de faire passer un message.
J'apprécie beaucoup ta contribution et je vais avoir besoin de ton aide pour Minetest.
Tu le connais bien mieux que moi.
Comme tu as pu le voir, j'ai fait un report complet des textures 0.4.14, la version actuelle.
J'apprécierais beaucoup que tu me fasses des remarques sur toutes les textures.
La vidéo m'a fait comprendre que j'avais fait ce pack trop rapidement, sans m'adapter aux spécificités de Minetest.
Je voudrais avoir la chance de sortir un vrai pack Minetest et demander au gars de refaire une review, sur un travail d'on on pourra être fière.
Merci de ton aide et désoler si j'ai été désagréable.

@tobyplowy, I hope you did not mistake my remark.
With the writing in addition to the approximate translation, it is difficult to give a message.
I appreciate your contribution very much and I will need your help for Minetest.
You know him better than I do.
As you could see, I made a complete report of textures 0.4.14, the current version.
I would appreciate it if you would comment on all the textures.
The video made me understand that I had made this pack too quickly, without adapting to the specificities of Minetest.
I would like to have the chance to get a real Minetest pack and ask the guy to do a review on a job we can be proud.
Thank you for your help and sorry if I was unpleasant.

**Comment by tobyplowy** [comment]
@lipki I am happy that you appreciate my work and it doesn't matter from yesterday I knew you were a bit pissed about me asking for Stuff but yeah you're forgiven :)

I need to thank you Because you Keep summerfields alive without you this pack wouldn't exist anymore or at least It Would not Be In The Good Looking staat is right now so Thanks i Mean it!

**Comment by tobyplowy** [comment]
@lipki I will be working on it tonight or tomorrow

**Comment by tobyplowy** [comment]
@lipki where is the issue for the corals? In case You didn't add Them yet here you can find it
https://github.com/minetest/minetest_game/blob/master/mods/default/textures/default_coral_brown.png https://github.com/minetest/minetest_game/blob/master/mods/default/textures/default_coral_skeleton.png https://github.com/minetest/minetest_game/blob/master/mods/default/textures/default_coral_orange.png
