### ISSUE TITLE
Dirt and grass

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#21]
![default_grass_side](https://cloud.githubusercontent.com/assets/401965/20409857/31f85872-ad1b-11e6-92fe-e18150d967d4.png)![default_grass](https://cloud.githubusercontent.com/assets/401965/20409850/31dc7774-ad1b-11e6-85b6-0a969d02dc3e.png)![default_grass_1](https://cloud.githubusercontent.com/assets/401965/20409851/31e1caa8-ad1b-11e6-8733-43a1e106208e.png)![default_grass_2](https://cloud.githubusercontent.com/assets/401965/20409853/31e7311e-ad1b-11e6-9c1c-c3b1f8499304.png)![default_grass_3](https://cloud.githubusercontent.com/assets/401965/20409852/31e6b0cc-ad1b-11e6-8e10-7f08ba6499cb.png)![default_grass_4](https://cloud.githubusercontent.com/assets/401965/20409854/31eb7c24-ad1b-11e6-9965-82f3dd788159.png)![default_grass_5](https://cloud.githubusercontent.com/assets/401965/20409855/31efb4ba-ad1b-11e6-9ed6-46fa0c8825eb.png)![default_junglegrass](https://cloud.githubusercontent.com/assets/401965/20409860/32026f38-ad1b-11e6-87d6-5d62f69dd738.png)
![default_dry_grass_side](https://cloud.githubusercontent.com/assets/401965/20409828/316f57fc-ad1b-11e6-93b8-f59cb32b1db4.png)![default_dry_grass](https://cloud.githubusercontent.com/assets/401965/20409822/314f77f2-ad1b-11e6-8029-bf84bc593d4d.png)![default_dry_grass_1](https://cloud.githubusercontent.com/assets/401965/20409824/31528410-ad1b-11e6-8fc7-514bc1c45fc8.png)![default_dry_grass_2](https://cloud.githubusercontent.com/assets/401965/20409823/3151f72a-ad1b-11e6-83ec-74797e97af34.png)![default_dry_grass_3](https://cloud.githubusercontent.com/assets/401965/20409825/315c6a02-ad1b-11e6-83e0-2905d8561495.png)![default_dry_grass_4](https://cloud.githubusercontent.com/assets/401965/20409827/316e7cba-ad1b-11e6-9c04-329f65dd4fca.png)![default_dry_grass_5](https://cloud.githubusercontent.com/assets/401965/20409826/316e4650-ad1b-11e6-9bef-e7f833b4f1a3.png)![default_dry_shrub](https://cloud.githubusercontent.com/assets/401965/20409829/31701688-ad1b-11e6-943e-32e12f4b1bf1.png)
![default_dirt](https://cloud.githubusercontent.com/assets/401965/20409821/314aad94-ad1b-11e6-8ebd-8e5e9d2f479f.png)

![farming_desert_sand_soil](https://cloud.githubusercontent.com/assets/401965/20411581/65ea2aa0-ad22-11e6-8715-a4e92e7ee58a.png)![farming_desert_sand_soil_wet](https://cloud.githubusercontent.com/assets/401965/20411582/65f94314-ad22-11e6-865d-1e50f82f8f56.png)![farming_desert_sand_soil_wet_side](https://cloud.githubusercontent.com/assets/401965/20411583/65fcc606-ad22-11e6-9398-b232948eebf3.png)
![farming_soil](https://cloud.githubusercontent.com/assets/401965/20411585/660e1ed8-ad22-11e6-8f13-127cb33e1a3d.png)![farming_soil_wet](https://cloud.githubusercontent.com/assets/401965/20411586/6612fc32-ad22-11e6-9ef2-2af0d8d98cb2.png)![farming_soil_wet_side](https://cloud.githubusercontent.com/assets/401965/20411587/6614957e-ad22-11e6-8ba3-d30fe0874994.png)

**Comment by lipki** [comment]
![default_grass_side](https://cloud.githubusercontent.com/assets/401965/20414252/cdbb7aa8-ad31-11e6-99b4-715fb461242b.png)![default_grass](https://cloud.githubusercontent.com/assets/401965/20414253/d0609770-ad31-11e6-89b7-10ec02c92406.png)![default_grass_1](https://cloud.githubusercontent.com/assets/401965/20414254/d08801ca-ad31-11e6-8825-1ab741fab3e9.png)![default_grass_2](https://cloud.githubusercontent.com/assets/401965/20414258/d3c3287e-ad31-11e6-8603-cc485ffbd569.png)![default_grass_3](https://cloud.githubusercontent.com/assets/401965/20414259/d3c80a10-ad31-11e6-9f2d-0c66e5d39d48.png)![default_grass_4](https://cloud.githubusercontent.com/assets/401965/20414260/d3f1ceae-ad31-11e6-9282-048aaf40a3a2.png)![default_grass_5](https://cloud.githubusercontent.com/assets/401965/20414261/d3f34b4e-ad31-11e6-8650-49799e74b19e.png)![default_junglegrass](https://cloud.githubusercontent.com/assets/401965/20414263/d5548f0c-ad31-11e6-8aac-3fb67b2a15cf.png)
![default_dry_grass_side](https://cloud.githubusercontent.com/assets/401965/20414272/e5cb588e-ad31-11e6-97e2-0131cde23ba9.png)![default_dry_grass](https://cloud.githubusercontent.com/assets/401965/20414273/e73fef04-ad31-11e6-804c-e740c32dbbf8.png)![default_dry_shrub](https://cloud.githubusercontent.com/assets/401965/20414281/efcc12ec-ad31-11e6-98fe-84eec9bc5064.png)![default_dry_grass_1](https://cloud.githubusercontent.com/assets/401965/20414275/eb1a1bc2-ad31-11e6-89a2-4b4ef344bb03.png)![default_dry_grass_2](https://cloud.githubusercontent.com/assets/401965/20414277/eb41cb72-ad31-11e6-979e-9010c79dbc6e.png)![default_dry_grass_3](https://cloud.githubusercontent.com/assets/401965/20414276/eb40b89a-ad31-11e6-9153-714262239e8a.png)![default_dry_grass_4](https://cloud.githubusercontent.com/assets/401965/20414278/eb490d92-ad31-11e6-8450-33506e46098f.png)![default_dry_grass_5](https://cloud.githubusercontent.com/assets/401965/20414279/ee53068c-ad31-11e6-9fec-d2262dcff087.png)
![default_dirt](https://cloud.githubusercontent.com/assets/401965/20414300/143b5ffc-ad32-11e6-925f-9de58a652b71.png)

![farming_desert_sand_soil](https://cloud.githubusercontent.com/assets/401965/20414309/224ea338-ad32-11e6-81dd-ccf3d058343d.png)![farming_desert_sand_soil_wet](https://cloud.githubusercontent.com/assets/401965/20414311/23f6cf1c-ad32-11e6-81f6-bb38e2f82d0e.png)![farming_desert_sand_soil_wet_side](https://cloud.githubusercontent.com/assets/401965/20414312/24206034-ad32-11e6-9b32-7984e64747ca.png)

![farming_soil](https://cloud.githubusercontent.com/assets/401965/20414313/26027ec8-ad32-11e6-8a3f-f0dc5afce391.png)![farming_soil_wet](https://cloud.githubusercontent.com/assets/401965/20414314/260a24ac-ad32-11e6-81de-8f855fccfa73.png)![farming_soil_wet_side](https://cloud.githubusercontent.com/assets/401965/20414315/26312eda-ad32-11e6-9104-9906031e4f9e.png)

**Comment by lipki** [comment]
![default_grass_side](https://cloud.githubusercontent.com/assets/401965/22215536/0dd3f450-e19c-11e6-89ff-01c8f96f634a.png)![default_dry_grass_side](https://cloud.githubusercontent.com/assets/401965/22215663/79db9194-e19c-11e6-8895-ff123084f6eb.png)

**Comment by tobyplowy** [comment]
@lipki I'm not shure about this new grass side can you show a little bit more dirt?

**Comment by tobyplowy** [comment]
@lipki i made a recolor for dry grass 
https://github.com/SummerFields/Minetest/pull/88
left old riht new
![recolor](https://cloud.githubusercontent.com/assets/16853304/22219950/0c2555d4-e1ad-11e6-8149-d4d7e1d63750.png)

**Comment by lipki** [comment]
![capture du 2017-01-24 16-23-57](https://cloud.githubusercontent.com/assets/401965/22253439/ee281cce-e251-11e6-91b2-8c6eec4f5018.png)

**Comment by tobyplowy** [comment]
@lipki Yes that is nice

**Comment by lipki** [comment]
ok done
