### ISSUE TITLE
Ice and snow

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#22]
![default_ice](https://cloud.githubusercontent.com/assets/401965/20409858/31fd604c-ad1b-11e6-8195-c52564ea0ebc.png)![default_snow](https://cloud.githubusercontent.com/assets/401965/20409917/330a10c0-ad1b-11e6-9431-f5fdd2cd2bae.png)![default_snowball](https://cloud.githubusercontent.com/assets/401965/20409916/3308cb8e-ad1b-11e6-8b3f-324c6d2d0ef3.png)![default_snow_side](https://cloud.githubusercontent.com/assets/401965/20409919/330f9036-ad1b-11e6-879c-75ad2f65ebd3.png)

**Comment by lipki** [comment]
![default_ice](https://cloud.githubusercontent.com/assets/401965/20414335/401e43e6-ad32-11e6-95ad-c0a85fd08e65.png)![default_snow](https://cloud.githubusercontent.com/assets/401965/20414339/4973b9c6-ad32-11e6-8635-a0b17feeca0a.png)![default_snowball](https://cloud.githubusercontent.com/assets/401965/20414340/4aaee93c-ad32-11e6-9a84-e9fb6948d46b.png)![default_snow_side](https://cloud.githubusercontent.com/assets/401965/20414344/4bdb7924-ad32-11e6-99d0-a56e6ba9e280.png)

**Comment by lipki** [comment]
![default_snow_side](https://cloud.githubusercontent.com/assets/401965/22215903/4640094a-e19d-11e6-875e-61d54031337c.png)
![capture du 2017-01-23 18-55-38](https://cloud.githubusercontent.com/assets/401965/22216022/adf614e4-e19d-11e6-94f9-cd6e8347a94d.png)

**Comment by tobyplowy** [comment]
@lipki that looks nice for the snow

**Comment by tobyplowy** [comment]
I think snow is abit too briht It's Almost pure White (rime not intended)

**Comment by lipki** [comment]
I have cleared up.
![default_snow](https://cloud.githubusercontent.com/assets/401965/22253863/5da1561e-e253-11e6-958c-38f10bed236e.png)![default_snow_side](https://cloud.githubusercontent.com/assets/401965/22253865/5f3714b4-e253-11e6-9305-a265a7b3becc.png)

![capture du 2017-01-24 16-32-05](https://cloud.githubusercontent.com/assets/401965/22253799/2e8352a6-e253-11e6-9f9b-5bd3b68e158d.png)

**Comment by tobyplowy** [comment]
@lipki I dount see what's different?

**Comment by lipki** [comment]
more white, test it

**Comment by tobyplowy** [comment]
@lipki I have not tested yet but more white why

**Comment by lipki** [comment]
Because I misunderstood what you said to me :)
I thought you wanted her whiter.

**Comment by tobyplowy** [comment]
@lipki No I whant less white XD

**Comment by lipki** [comment]
do it

**Comment by tobyplowy** [comment]
@lipki ok

**Comment by tobyplowy** [comment]
@lipki 
default_snow
![default_snow](https://cloud.githubusercontent.com/assets/16853304/22259284/f976f20e-e264-11e6-922e-4233067132cc.png)
default_snow_side
![default_snow_side](https://cloud.githubusercontent.com/assets/16853304/22259283/f976ef02-e264-11e6-9d38-4b3ab94df7a2.png)

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by lipki** [comment]
ok

**Comment by tobyplowy** [comment]
@lipki close?

**Comment by lipki** [comment]
Only when the commit is done.
