### ISSUE TITLE
stone

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#23]
![default_mossycobble](https://cloud.githubusercontent.com/assets/401965/20409885/3275e4e0-ad1b-11e6-9ac3-53954f5a949f.png)![default_cobble](https://cloud.githubusercontent.com/assets/401965/20409811/31145faa-ad1b-11e6-9d72-8cc11481e6a3.png)![default_stone](https://cloud.githubusercontent.com/assets/401965/20409922/3320801c-ad1b-11e6-8326-36e08d04398a.png)![default_stone_brick](https://cloud.githubusercontent.com/assets/401965/20409923/3321fbfe-ad1b-11e6-9203-043e7e7f9ad6.png)

![default_tool_stoneaxe](https://cloud.githubusercontent.com/assets/401965/20409939/336a7f0a-ad1b-11e6-9a30-42647be5109a.png)![default_tool_stonepick](https://cloud.githubusercontent.com/assets/401965/20409941/336fa26e-ad1b-11e6-975c-b8469dd7a340.png)![default_tool_stoneshovel](https://cloud.githubusercontent.com/assets/401965/20409942/3371d066-ad1b-11e6-89e2-44918f621914.png)![default_tool_stonesword](https://cloud.githubusercontent.com/assets/401965/20409943/33790fac-ad1b-11e6-8400-0a1642ca8080.png)![farming_tool_stonehoe](https://cloud.githubusercontent.com/assets/401965/20411594/66334e24-ad22-11e6-85ed-d28cd301277b.png)

**Comment by lipki** [comment]
![default_mossycobble](https://cloud.githubusercontent.com/assets/401965/20414369/6031ded6-ad32-11e6-85a6-91867f5ae0ec.png)![default_cobble](https://cloud.githubusercontent.com/assets/401965/20414374/63961178-ad32-11e6-88b2-3dcac2fb7fb1.png)![default_stone](https://cloud.githubusercontent.com/assets/401965/20414378/685fdc16-ad32-11e6-8c91-b49f27210bcc.png)![default_stone_brick](https://cloud.githubusercontent.com/assets/401965/20414380/6a46226a-ad32-11e6-8ce7-ead77f4f016b.png)

![default_tool_stoneaxe](https://cloud.githubusercontent.com/assets/401965/20414389/768c95ae-ad32-11e6-831b-e2c3dc73a4c3.png)![default_tool_stonepick](https://cloud.githubusercontent.com/assets/401965/20414390/768ffc08-ad32-11e6-8382-e5c37ee3e1d3.png)![default_tool_stoneshovel](https://cloud.githubusercontent.com/assets/401965/20414392/7693766c-ad32-11e6-9fb3-8698792dbf17.png)![default_tool_stonesword](https://cloud.githubusercontent.com/assets/401965/20414391/7691d2f8-ad32-11e6-9519-981775c69b0e.png)![farming_tool_stonehoe](https://cloud.githubusercontent.com/assets/401965/20414397/78af5ba0-ad32-11e6-98b7-0020bd54d88b.png)

**Comment by tobyplowy** [comment]
@lipki please use this as mossy cobble
![cobblestone_mossy](https://cloud.githubusercontent.com/assets/16853304/20458884/69d07a80-aeb1-11e6-91c1-b7590092dd33.png)

**Comment by lipki** [comment]
Yes I do not know why I forget to change that.

**Comment by tobyplowy** [comment]
@lipki XD

**Comment by lipki** [comment]
it's done
