### ISSUE TITLE
sand

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#24]
![default_gravel](https://cloud.githubusercontent.com/assets/401965/20409856/31f76232-ad1b-11e6-8b65-d5c08e24530d.png)![default_sand](https://cloud.githubusercontent.com/assets/401965/20409908/32d798de-ad1b-11e6-899c-3337562863f9.png)![default_sandstone](https://cloud.githubusercontent.com/assets/401965/20409909/32ebcf84-ad1b-11e6-8924-ba07ddf586f9.png)![default_sandstone_brick](https://cloud.githubusercontent.com/assets/401965/20409910/32ed23a2-ad1b-11e6-99eb-248bdb45494d.png)

![default_desert_cobble](https://cloud.githubusercontent.com/assets/401965/20409815/311ed1b0-ad1b-11e6-8752-0b0b4ccb9f76.png)![default_desert_sand](https://cloud.githubusercontent.com/assets/401965/20409817/312afbac-ad1b-11e6-9622-3a21b4cb95e2.png)![default_desert_stone](https://cloud.githubusercontent.com/assets/401965/20409816/312afa62-ad1b-11e6-9e7b-36b95881eb56.png)![default_desert_stone_brick](https://cloud.githubusercontent.com/assets/401965/20409818/313f7122-ad1b-11e6-9cc5-8b3b85a451a9.png)

**Comment by lipki** [comment]
![default_gravel](https://cloud.githubusercontent.com/assets/401965/20414411/8e419c62-ad32-11e6-9006-233e516998ad.png)![default_sand](https://cloud.githubusercontent.com/assets/401965/20414413/91fadeae-ad32-11e6-9f26-b1c9348b8e61.png)![default_sandstone](https://cloud.githubusercontent.com/assets/401965/20414414/9363ab90-ad32-11e6-8d02-82359859fcb3.png)![default_sandstone_brick](https://cloud.githubusercontent.com/assets/401965/20414416/9481250c-ad32-11e6-8ff1-a596625bf219.png)

**Comment by lipki** [comment]
by @tobyplowy 
default_sandstone_block
![default_sandstone_block](https://cloud.githubusercontent.com/assets/16853304/20282302/7cb4e63c-aab4-11e6-94be-2c3bf79e7cea.png)

**Comment by tobyplowy** [comment]
@lipki please use this as gravel
![gravel3](https://cloud.githubusercontent.com/assets/16853304/20458946/a2bfc7aa-aeb2-11e6-86fd-f5bdb1a6e89a.png)

**Comment by tobyplowy** [comment]
@lipki also use this texture for the minecraft pack 
![gravel3](https://cloud.githubusercontent.com/assets/16853304/20458964/db96fe68-aeb2-11e6-9d15-fb928ca04bba.png)

**Comment by lipki** [comment]
Good try: D

**Comment by tobyplowy** [comment]
@lipki lol Why Not The Texture that is used now Looks To repetatif What should we do with it

**Comment by lipki** [comment]
Because it's too big gravel.
Looks like a pebble.

**Comment by tobyplowy** [comment]
@lipki can you make the gravel texture look like the dead coral you made
![3565e626-e111-11e6-9dfb-3e434697bdee](https://cloud.githubusercontent.com/assets/16853304/22216398/3f990522-e19f-11e6-89ce-7a18834e8de0.png)

**Comment by lipki** [comment]
still too big

![default_gravel](https://cloud.githubusercontent.com/assets/401965/22216869/07afc1a8-e1a1-11e6-8b0d-e274c8fcbf49.png)

![capture du 2017-01-23 19-18-02](https://cloud.githubusercontent.com/assets/401965/22216883/190a10a2-e1a1-11e6-8491-2e504c21318b.png)

???

**Comment by tobyplowy** [comment]
@lipki i will try to make a better one later

**Comment by lipki** [comment]
ok

**Comment by tobyplowy** [comment]
@lipki hows this?
![gravel](https://cloud.githubusercontent.com/assets/16853304/22220577/833f8354-e1af-11e6-98ee-8eda9fdd56c1.png)
![gravel](https://cloud.githubusercontent.com/assets/16853304/22220601/900ae5c4-e1af-11e6-9c99-28efab9c718e.png)

**Comment by lipki** [comment]
I'm not sure, it's blurry, but I like it, I think we'll test it on minetest a moment.

**Comment by tobyplowy** [comment]
@lipki maybe you can improve it?

**Comment by lipki** [comment]
for now it's done.

**Comment by tobyplowy** [comment]
Ok
