### ISSUE TITLE
coal

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#27]
![default_mineral_coal](https://cloud.githubusercontent.com/assets/401965/20409878/3258d832-ad1b-11e6-93f4-01d7e9aea0a7.png)![default_coal_block](https://cloud.githubusercontent.com/assets/401965/20409809/310a18e2-ad1b-11e6-829a-88fc5a4fb4c4.png)![default_coal_lump](https://cloud.githubusercontent.com/assets/401965/20409810/31123356-ad1b-11e6-9c0e-465329968979.png)

**Comment by lipki** [comment]
![default_mineral_coal](https://cloud.githubusercontent.com/assets/401965/20414477/eb442f4c-ad32-11e6-8fa5-c3c4f4b62888.png)![default_coal_block](https://cloud.githubusercontent.com/assets/401965/20414479/ee7e9c4c-ad32-11e6-984d-8ca4580291f7.png)![default_coal_lump](https://cloud.githubusercontent.com/assets/401965/20414480/f05d2998-ad32-11e6-9606-8866238439a7.png)

**Comment by tobyplowy** [comment]
@lipki please add this as coal 
![coal_ore](https://cloud.githubusercontent.com/assets/16853304/20577090/02c38860-b1c1-11e6-8f8d-f605553c52d1.png)

**Comment by tobyplowy** [comment]
@lipki also i downt like the coal block (btw i also downt like the minecraft coal block this one 
![coal_block](https://cloud.githubusercontent.com/assets/16853304/20577135/40790b76-b1c1-11e6-9998-f740a40f8c99.png))

**Comment by lipki** [comment]
An addition of @ImLeeRii, better than the old I find.

**Comment by lipki** [comment]
![default_mineral_coal](https://cloud.githubusercontent.com/assets/401965/22266402/28577880-e280-11e6-9903-cb5d93987a87.png)
