### ISSUE TITLE
clay

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#28]
![default_clay](https://cloud.githubusercontent.com/assets/401965/20409804/30ed94b0-ad1b-11e6-8c69-6ee52854c2df.png)![default_clay_brick](https://cloud.githubusercontent.com/assets/401965/20409806/30f71486-ad1b-11e6-8ad2-1dd5ab4fa809.png)![default_clay_lump](https://cloud.githubusercontent.com/assets/401965/20409807/30fb0e10-ad1b-11e6-9745-edf346a1fb6e.png)![default_brick](https://cloud.githubusercontent.com/assets/401965/20409796/30c59fc8-ad1b-11e6-9827-501d94cc5a9c.png)

**Comment by lipki** [comment]
![default_clay](https://cloud.githubusercontent.com/assets/401965/20414490/fafdf36e-ad32-11e6-9112-fff7fb2ed83e.png)![default_clay_brick](https://cloud.githubusercontent.com/assets/401965/20414492/fc4f88f4-ad32-11e6-8ffa-9ea8511feea8.png)![default_clay_lump](https://cloud.githubusercontent.com/assets/401965/20414493/fd9382c4-ad32-11e6-9d45-5cef67520ac2.png)![default_brick](https://cloud.githubusercontent.com/assets/401965/20414495/fe90e16c-ad32-11e6-84d7-38992f56e920.png)

**Comment by tobyplowy** [comment]
@lipki this is good :D

**Comment by lipki** [comment]
yes
