### ISSUE TITLE
copper

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#29]
![default_mineral_copper](https://cloud.githubusercontent.com/assets/401965/20409880/32616bfa-ad1b-11e6-9489-60d795727677.png)![default_copper_block](https://cloud.githubusercontent.com/assets/401965/20409813/3117490e-ad1b-11e6-9509-aa005af33dfb.png)![default_copper_ingot](https://cloud.githubusercontent.com/assets/401965/20409812/3116396a-ad1b-11e6-9621-c5dccc07f1c8.png)![default_copper_lump](https://cloud.githubusercontent.com/assets/401965/20409814/3118d288-ad1b-11e6-9050-1057942df98d.png)

**Comment by lipki** [comment]
![default_mineral_copper](https://cloud.githubusercontent.com/assets/401965/20414506/0d9d10c2-ad33-11e6-937f-c75652366b54.png)![default_copper_block](https://cloud.githubusercontent.com/assets/401965/20414509/0f4a7a7c-ad33-11e6-9637-5fc0a126ff5a.png)![default_copper_ingot](https://cloud.githubusercontent.com/assets/401965/20414512/10822a70-ad33-11e6-8ac2-edb908f8ed29.png)![default_copper_lump](https://cloud.githubusercontent.com/assets/401965/20414513/13152c24-ad33-11e6-881a-200e97382c0e.png)

**Comment by lipki** [comment]
![default_mineral_copper](https://cloud.githubusercontent.com/assets/401965/22262359/e3ddbac0-e270-11e6-96cc-da6897bbf046.png)

**Comment by tobyplowy** [comment]
@lipki done?
