### ISSUE TITLE
gold

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#32]
![default_mineral_gold](https://cloud.githubusercontent.com/assets/401965/20409882/3271dbe8-ad1b-11e6-829e-f34abeccddc0.png)![default_gold_block](https://cloud.githubusercontent.com/assets/401965/20409848/31cad208-ad1b-11e6-9130-3664cfd9d30f.png)![default_gold_ingot](https://cloud.githubusercontent.com/assets/401965/20409847/31c8d106-ad1b-11e6-9973-c5b3879bdb8e.png)![default_gold_lump](https://cloud.githubusercontent.com/assets/401965/20409849/31d91f8e-ad1b-11e6-974d-13580e13f885.png)

**Comment by lipki** [comment]
![default_mineral_gold](https://cloud.githubusercontent.com/assets/401965/20414630/a5f81808-ad33-11e6-9990-15af0a0283d0.png)![default_gold_block](https://cloud.githubusercontent.com/assets/401965/20414632/a7c1038e-ad33-11e6-8a7a-1d9fc983e7b0.png)![default_gold_ingot](https://cloud.githubusercontent.com/assets/401965/20414633/a91653ce-ad33-11e6-894d-ee3eb5cb3a5e.png)![default_gold_lump](https://cloud.githubusercontent.com/assets/401965/20414634/aae25338-ad33-11e6-81e8-6d31e3ef4521.png)

**Comment by lipki** [comment]
![moreores_tool_goldaxe](https://cloud.githubusercontent.com/assets/401965/20449644/f7b4687e-adea-11e6-8297-9a6c193181c7.png)![moreores_tool_goldpick](https://cloud.githubusercontent.com/assets/401965/20449639/f43b4a00-adea-11e6-80ca-cadc426bacb5.png)![moreores_tool_goldshovel](https://cloud.githubusercontent.com/assets/401965/20449641/f46468c2-adea-11e6-9d48-2dd1c340f4fc.png)![moreores_tool_goldsword](https://cloud.githubusercontent.com/assets/401965/20449642/f4684168-adea-11e6-9b30-0ffc7db64621.png)

**Comment by lipki** [comment]
![default_mineral_gold](https://cloud.githubusercontent.com/assets/401965/22262570/c9e90c68-e271-11e6-9f26-9d5a8d0b5b59.png)

**Comment by tobyplowy** [comment]
@lipki done?
