### ISSUE TITLE
mese

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#34]
![default_mineral_mese](https://cloud.githubusercontent.com/assets/401965/20409884/327591a2-ad1b-11e6-9623-3c5abfc455d0.png)![default_mese_block](https://cloud.githubusercontent.com/assets/401965/20409874/324ba7d4-ad1b-11e6-9b8a-e8f5900938e1.png)![default_mese_crystal](https://cloud.githubusercontent.com/assets/401965/20409875/324cc0a6-ad1b-11e6-96ee-5ac6c5f50dfa.png)![default_mese_crystal_fragment](https://cloud.githubusercontent.com/assets/401965/20409876/324fa668-ad1b-11e6-80df-21db7590b535.png)![default_meselamp](https://cloud.githubusercontent.com/assets/401965/20409877/325644b4-ad1b-11e6-9d23-07f48ee1e1f2.png)

![default_tool_meseaxe](https://cloud.githubusercontent.com/assets/401965/20409932/334a7d18-ad1b-11e6-80c5-f5f377eddd50.png)![default_tool_mesepick](https://cloud.githubusercontent.com/assets/401965/20409933/334dd1c0-ad1b-11e6-898c-b225ddd29175.png)![default_tool_meseshovel](https://cloud.githubusercontent.com/assets/401965/20409934/334f14f4-ad1b-11e6-821f-635c2b1a488b.png)![default_tool_mesesword](https://cloud.githubusercontent.com/assets/401965/20409935/334fae82-ad1b-11e6-97bd-331639fb0560.png)![farming_tool_mesehoe](https://cloud.githubusercontent.com/assets/401965/20411593/663202a8-ad22-11e6-8a45-63bd814be45b.png)

**Comment by lipki** [comment]
![default_mineral_mese](https://cloud.githubusercontent.com/assets/401965/20414674/e9ac11b2-ad33-11e6-8ec9-3d1eed856575.png)![default_mese_block](https://cloud.githubusercontent.com/assets/401965/20414676/eb42167a-ad33-11e6-8e10-6f6dc9bf15ce.png)![default_mese_crystal](https://cloud.githubusercontent.com/assets/401965/20414679/ecd2fc52-ad33-11e6-8001-6cc4434a3b47.png)![default_mese_crystal_fragment](https://cloud.githubusercontent.com/assets/401965/20414681/ee1d82d0-ad33-11e6-9ff7-e35cc17143b5.png)![default_meselamp](https://cloud.githubusercontent.com/assets/401965/20414682/ef5715ee-ad33-11e6-8b3a-38be03f75701.png)
![default_tool_meseaxe](https://cloud.githubusercontent.com/assets/401965/20414686/f655bd14-ad33-11e6-8dfe-f59b39ccdb53.png)![default_tool_mesepick](https://cloud.githubusercontent.com/assets/401965/20414687/f6582b1c-ad33-11e6-9356-8846ac41969c.png)![default_tool_meseshovel](https://cloud.githubusercontent.com/assets/401965/20414688/f80710c2-ad33-11e6-9488-0ce040087c58.png)![default_tool_mesesword](https://cloud.githubusercontent.com/assets/401965/20414689/f8174622-ad33-11e6-9277-e2838185986e.png)![farming_tool_mesehoe](https://cloud.githubusercontent.com/assets/401965/20414691/f92a075c-ad33-11e6-8bd9-1edb85265b24.png)

**Comment by tobyplowy** [comment]
mese lamp 
![redstone_lamp_on_fixe](https://cloud.githubusercontent.com/assets/16853304/20459065/ca510894-aeb5-11e6-9562-544fcb234f12.png)

i cant get the color acurate to this one
![ef5715ee-ad33-11e6-8b3a-38be03f75701](https://cloud.githubusercontent.com/assets/16853304/20459071/e3b6c616-aeb5-11e6-8c45-f3e8d860d211.png)
can you give it a try

**Comment by lipki** [comment]
![default_meselamp](https://cloud.githubusercontent.com/assets/401965/22263107/a1b64a88-e273-11e6-8219-73fb83dae997.png)

**Comment by tobyplowy** [comment]
@lipki yes I like that!

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by lipki** [comment]
yes
