### ISSUE TITLE
tree

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#36]
![default_leaves](https://cloud.githubusercontent.com/assets/401965/20409872/323f0fce-ad1b-11e6-9542-4dd298be44df.png)![default_leaves_simple](https://cloud.githubusercontent.com/assets/401965/20409873/32408a52-ad1b-11e6-8c98-b01684f5a9ec.png)![default_sapling](https://cloud.githubusercontent.com/assets/401965/20409912/32f17ca4-ad1b-11e6-825d-21c4d6865b34.png)![default_tree](https://cloud.githubusercontent.com/assets/401965/20409952/339b1340-ad1b-11e6-9263-a7d5d7769221.png)![default_tree_top](https://cloud.githubusercontent.com/assets/401965/20409953/33a05f8a-ad1b-11e6-9ac5-9273cc9432e2.png)![default_wood](https://cloud.githubusercontent.com/assets/401965/20409957/33b23d9a-ad1b-11e6-976f-0aa1432a5a4b.png)![default_fence_wood](https://cloud.githubusercontent.com/assets/401965/20409834/318d6602-ad1b-11e6-8f5e-7a8a0282cd09.png)
![default_acacia_leaves](https://cloud.githubusercontent.com/assets/401965/20409782/3084d9a2-ad1b-11e6-965d-1a049db2fbc4.png)![default_acacia_sapling](https://cloud.githubusercontent.com/assets/401965/20409783/3089126a-ad1b-11e6-90f6-ec57daaabe21.png)![default_acacia_tree](https://cloud.githubusercontent.com/assets/401965/20409790/30acf090-ad1b-11e6-95cf-f6a246bfa9d1.png)![default_acacia_tree_top](https://cloud.githubusercontent.com/assets/401965/20409788/30a4a944-ad1b-11e6-9697-dcd0dd26a134.png)![default_acacia_wood](https://cloud.githubusercontent.com/assets/401965/20409784/30945864-ad1b-11e6-9bfd-5f7a1797f71b.png)![default_fence_acacia_wood](https://cloud.githubusercontent.com/assets/401965/20409830/31763e50-ad1b-11e6-9ca6-01725bde5edc.png)
![default_aspen_leaves](https://cloud.githubusercontent.com/assets/401965/20409786/30a04ad4-ad1b-11e6-8a36-40d661e059b6.png)![default_aspen_sapling](https://cloud.githubusercontent.com/assets/401965/20409787/30a156ae-ad1b-11e6-8608-67783c744e76.png)![default_aspen_tree](https://cloud.githubusercontent.com/assets/401965/20409789/30a64e52-ad1b-11e6-8a0f-5ebbfd310fa6.png)![default_aspen_tree_top](https://cloud.githubusercontent.com/assets/401965/20409791/30b35430-ad1b-11e6-838c-1da430f29556.png)![default_aspen_wood](https://cloud.githubusercontent.com/assets/401965/20409792/30b3705a-ad1b-11e6-9379-48a1793eb1d7.png)![default_fence_aspen_wood](https://cloud.githubusercontent.com/assets/401965/20409832/318627e8-ad1b-11e6-8cce-b312fae81847.png)
![default_jungleleaves](https://cloud.githubusercontent.com/assets/401965/20409861/320d3c2e-ad1b-11e6-99da-fce4f5651fed.png)![default_jungleleaves_simple](https://cloud.githubusercontent.com/assets/401965/20409862/3212bcb2-ad1b-11e6-8a3d-e3f174814224.png)![default_junglesapling](https://cloud.githubusercontent.com/assets/401965/20409863/32141760-ad1b-11e6-9d91-552504cfa4ce.png)![default_jungletree](https://cloud.githubusercontent.com/assets/401965/20409864/3217921e-ad1b-11e6-9f5a-3129d37ffa6c.png)![default_jungletree_top](https://cloud.githubusercontent.com/assets/401965/20409865/321cf8ee-ad1b-11e6-8171-41e0cdef070e.png)![default_junglewood](https://cloud.githubusercontent.com/assets/401965/20409866/32203cd4-ad1b-11e6-9197-bbe34857a34e.png)![default_fence_junglewood](https://cloud.githubusercontent.com/assets/401965/20409831/31859850-ad1b-11e6-9050-c2b2d03bc135.png)
![default_pine_needles](https://cloud.githubusercontent.com/assets/401965/20409896/32adf894-ad1b-11e6-97d7-dedd3ef1c0b7.png)![default_pine_sapling](https://cloud.githubusercontent.com/assets/401965/20409897/32b03a96-ad1b-11e6-9fbe-39d640891d8e.png)![default_pine_tree](https://cloud.githubusercontent.com/assets/401965/20409898/32b4daba-ad1b-11e6-98e0-0b32162e78cd.png)![default_pine_tree_top](https://cloud.githubusercontent.com/assets/401965/20409900/32b8aabe-ad1b-11e6-9843-cbc37744d1f4.png)![default_pine_wood](https://cloud.githubusercontent.com/assets/401965/20409899/32b6ca0a-ad1b-11e6-9bea-fd720bcf140b.png)![default_fence_pine_wood](https://cloud.githubusercontent.com/assets/401965/20409833/318ba2fe-ad1b-11e6-8af3-f7948c0181df.png)

![default_fence_overlay](https://cloud.githubusercontent.com/assets/401965/20409835/318e8f78-ad1b-11e6-8ba2-31ec8f7f1523.png)

**Comment by lipki** [comment]
![default_leaves](https://cloud.githubusercontent.com/assets/401965/20413687/9bbec788-ad2e-11e6-9ed6-82cc7682bb5e.png)![default_leaves_simple](https://cloud.githubusercontent.com/assets/401965/20413688/9bc437f4-ad2e-11e6-86be-d84e10dd293d.png)![default_sapling](https://cloud.githubusercontent.com/assets/401965/20413713/be751a84-ad2e-11e6-87bd-738f9038b791.png)![default_tree](https://cloud.githubusercontent.com/assets/401965/20413712/be5b6cb0-ad2e-11e6-81fd-31b3a4786878.png)![default_tree_top](https://cloud.githubusercontent.com/assets/401965/20413711/be588982-ad2e-11e6-8123-79987c9bfd89.png)![default_wood](https://cloud.githubusercontent.com/assets/401965/20413714/be77d83c-ad2e-11e6-9510-d58d5ba34cf3.png)![default_fence_wood](https://cloud.githubusercontent.com/assets/401965/20413721/cd175336-ad2e-11e6-8db4-a2d52effbafb.png)
![default_acacia_leaves](https://cloud.githubusercontent.com/assets/401965/20413748/ff85d0c2-ad2e-11e6-901c-159662bc1bbc.png)![default_acacia_sapling](https://cloud.githubusercontent.com/assets/401965/20413751/025041f2-ad2f-11e6-86ef-eb2a2fe837f0.png)![default_acacia_tree](https://cloud.githubusercontent.com/assets/401965/20413752/02782f82-ad2f-11e6-95e3-b3f6e273183e.png)![default_acacia_tree_top](https://cloud.githubusercontent.com/assets/401965/20413753/027bb62a-ad2f-11e6-923d-557e53314cfb.png)![default_acacia_wood](https://cloud.githubusercontent.com/assets/401965/20413754/02819658-ad2f-11e6-88f4-43c738f6d40e.png)![default_fence_acacia_wood](https://cloud.githubusercontent.com/assets/401965/20413756/03e18ca6-ad2f-11e6-9399-c74679db9221.png)
![default_aspen_leaves](https://cloud.githubusercontent.com/assets/401965/20413770/1ce950e4-ad2f-11e6-9a6b-eaf4550e4f1e.png)![default_aspen_sapling](https://cloud.githubusercontent.com/assets/401965/20413772/1cecf0be-ad2f-11e6-86a1-fcf2ef1b783d.png)![default_aspen_tree](https://cloud.githubusercontent.com/assets/401965/20413769/1ce67216-ad2f-11e6-83be-faba0ffc763f.png)![default_aspen_tree_top](https://cloud.githubusercontent.com/assets/401965/20413771/1cea8ec8-ad2f-11e6-987e-0342ebef6517.png)![default_aspen_wood](https://cloud.githubusercontent.com/assets/401965/20413773/1cf71364-ad2f-11e6-90c4-0f8a1aaf3ccf.png)![default_fence_aspen_wood](https://cloud.githubusercontent.com/assets/401965/20413774/1cfaff56-ad2f-11e6-8958-851b3e433acb.png)
![default_jungleleaves](https://cloud.githubusercontent.com/assets/401965/20413782/2d96f54a-ad2f-11e6-955a-033df0c1410b.png)![default_jungleleaves_simple](https://cloud.githubusercontent.com/assets/401965/20413783/2d99cd7e-ad2f-11e6-9ae9-38b12f8bdb25.png)![default_junglesapling](https://cloud.githubusercontent.com/assets/401965/20413784/2f0a17d6-ad2f-11e6-94cb-5ad9d59f8a9c.png)![default_jungletree](https://cloud.githubusercontent.com/assets/401965/20413786/321e48fc-ad2f-11e6-8267-5119eda37cb6.png)![default_jungletree_top](https://cloud.githubusercontent.com/assets/401965/20413787/321fd8a2-ad2f-11e6-8da5-d6e2bda8ff88.png)![default_junglewood](https://cloud.githubusercontent.com/assets/401965/20413789/324b7cd2-ad2f-11e6-9938-23cee610d830.png)![default_fence_junglewood](https://cloud.githubusercontent.com/assets/401965/20413790/3411bd06-ad2f-11e6-8eb7-ee3a53445690.png)
![default_pine_needles](https://cloud.githubusercontent.com/assets/401965/20413797/42fef752-ad2f-11e6-87dc-4c7d1af563cb.png)![default_pine_sapling](https://cloud.githubusercontent.com/assets/401965/20413799/443710d2-ad2f-11e6-8a2f-5210eb8245c8.png)![default_pine_tree](https://cloud.githubusercontent.com/assets/401965/20413803/4615f30a-ad2f-11e6-8f02-445fa217ffb6.png)![default_pine_tree_top](https://cloud.githubusercontent.com/assets/401965/20413804/4640b75c-ad2f-11e6-9ff9-d59b84c68eda.png)![default_pine_wood](https://cloud.githubusercontent.com/assets/401965/20413812/4771c3dc-ad2f-11e6-8a97-57adf3f3ebe6.png)![default_fence_pine_wood](https://cloud.githubusercontent.com/assets/401965/20413813/488a1ef4-ad2f-11e6-9f89-43945d777525.png)

![default_fence_overlay](https://cloud.githubusercontent.com/assets/401965/20413828/5bef4fe6-ad2f-11e6-877b-08b006a2f309.png)

**Comment by lipki** [comment]
by @tobyplowy 
new wood closer to original minetest wood
NOTE oak stays the same 
default_acacia_wood
![default_acacia_wood](https://cloud.githubusercontent.com/assets/16853304/20282218/2aa8e712-aab4-11e6-9d32-71bfcb19b2cc.png)
default_aspen_wood
![default_aspen_wood](https://cloud.githubusercontent.com/assets/16853304/20282219/2ac20dd2-aab4-11e6-80ec-3db7b1b41aca.png)
default_junglewood
![default_junglewood](https://cloud.githubusercontent.com/assets/16853304/20282221/2ac8b6c8-aab4-11e6-8f7a-ba938cfe1454.png)
default_pine_wood
![default_pine_wood](https://cloud.githubusercontent.com/assets/16853304/20282220/2ac6d83a-aab4-11e6-94b1-fb7852213a32.png)

**Comment by tobyplowy** [comment]
working on new tree recolors

**Comment by tobyplowy** [comment]
default_acacia_tree_top
![default_acacia_tree_top](https://cloud.githubusercontent.com/assets/16853304/20450432/e180b200-adf0-11e6-999f-e398a0cc973a.png)
default_acacia_tree
![default_acacia_tree](https://cloud.githubusercontent.com/assets/16853304/20450433/e181acc8-adf0-11e6-9663-3aec68e9ecc2.png)

**Comment by tobyplowy** [comment]
default_tree
![default_tree](https://cloud.githubusercontent.com/assets/16853304/20450648/3d351f72-adf2-11e6-8dd3-b2fa6a4d2305.png)
default_tree_top
![default_tree_top](https://cloud.githubusercontent.com/assets/16853304/20450649/3d496496-adf2-11e6-9652-9323480631b6.png)

**Comment by tobyplowy** [comment]
default_jungletree
![default_jungletree](https://cloud.githubusercontent.com/assets/16853304/20450731/f4e8b4da-adf2-11e6-887c-702aa5fb8f55.png)
default_jungletree_top
![default_jungletree_top](https://cloud.githubusercontent.com/assets/16853304/20450732/f4ee48a0-adf2-11e6-9693-93b68460b258.png)

**Comment by tobyplowy** [comment]
@lipki trees are done
![minetest new wood](https://cloud.githubusercontent.com/assets/16853304/20451049/a96e6bbe-adf5-11e6-81b7-e7e38b181aff.png)
lipki what do you think

default_acacia_tree
![default_acacia_tree](https://cloud.githubusercontent.com/assets/16853304/20451021/7519fcde-adf5-11e6-8277-dbd78bf29089.png)
default_acacia_tree_top
![default_acacia_tree_top](https://cloud.githubusercontent.com/assets/16853304/20451018/73667b60-adf5-11e6-9a2a-216d4a03cb6b.png)

default_aspen_tree
![default_aspen_tree](https://cloud.githubusercontent.com/assets/16853304/20451027/79fc90fe-adf5-11e6-9fa2-c544d0c969a1.png)
default_aspen_tree_top
![default_aspen_tree_top](https://cloud.githubusercontent.com/assets/16853304/20451028/7a1181ee-adf5-11e6-924a-cc1d56bb76d0.png)

default_jungletree
![default_jungletree](https://cloud.githubusercontent.com/assets/16853304/20451030/7ef270f6-adf5-11e6-9b89-9afcdacab800.png)
default_jungletree_top
![default_jungletree_top](https://cloud.githubusercontent.com/assets/16853304/20451031/7ef33d24-adf5-11e6-83d2-0c655f201fad.png)

default_pine_tree
![default_pine_tree](https://cloud.githubusercontent.com/assets/16853304/20451033/81b96894-adf5-11e6-8c62-0f1079dee123.png)
default_pine_tree_top
![default_pine_tree_top](https://cloud.githubusercontent.com/assets/16853304/20451032/81b8f1c0-adf5-11e6-8275-be02a3a9422c.png)

default_tree
![default_tree](https://cloud.githubusercontent.com/assets/16853304/20451036/84e0a5aa-adf5-11e6-910e-78fd8bef8683.png)
default_tree_top
![default_tree_top](https://cloud.githubusercontent.com/assets/16853304/20451037/84e6630a-adf5-11e6-8ec3-dc5fbda965e2.png)

**Comment by tobyplowy** [comment]
@lipki fences done
default_fence_acacia_wood
![default_fence_acacia_wood](https://cloud.githubusercontent.com/assets/16853304/20451310/160da90e-adf8-11e6-99a7-4e2a197df1d8.png)
default_fence_aspen_wood
![default_fence_aspen_wood](https://cloud.githubusercontent.com/assets/16853304/20451311/16220a52-adf8-11e6-9475-6094a9e32b85.png)
default_fence_junglewood
![default_fence_junglewood](https://cloud.githubusercontent.com/assets/16853304/20451312/16365d7c-adf8-11e6-93dd-a7c6c40fbc85.png)
default_fence_pine_wood
![default_fence_pine_wood](https://cloud.githubusercontent.com/assets/16853304/20451313/16478e12-adf8-11e6-965e-8fa95bf9c4d3.png)
default_fence_wood
![default_fence_wood](https://cloud.githubusercontent.com/assets/16853304/20451314/16482656-adf8-11e6-9c5c-40edb14ba3c6.png)

**Comment by tobyplowy** [comment]
@lipki in my opinion leafs shuld stay the same also i will do the saplings later (its to late i have to sleap its 1:37 at niht XD)

**Comment by lipki** [comment]
Yes, that's fine.
Maybe to clear a little the planks of aspen and pine.
But that's already good.

**Comment by lipki** [comment]
![default_fence_overlay](https://cloud.githubusercontent.com/assets/401965/20644991/2e79dd64-b44c-11e6-9ac5-3f30272e2c2c.png)

**Comment by tobyplowy** [comment]
@lipki also can you recolor the Aspen and pine planks?

**Comment by tobyplowy** [comment]
Also Nice new fence texture :)

**Comment by lipki** [comment]
![default_acacia_leaves_simple](https://cloud.githubusercontent.com/assets/401965/22263479/e49c7c90-e274-11e6-99d1-e76068f5bbf4.png)![default_leaves_simple](https://cloud.githubusercontent.com/assets/401965/22263502/fabcf34c-e274-11e6-8bf6-f7fe7b95d651.png)
![default_acacia_bush_stem](https://cloud.githubusercontent.com/assets/401965/22263467/d8efb2ae-e274-11e6-9980-70a49d25b568.png)![default_bush_stem](https://cloud.githubusercontent.com/assets/401965/22263470/db369b18-e274-11e6-8b19-ae889b98c5c2.png)

**Comment by lipki** [comment]
![default_fence_aspen_wood](https://cloud.githubusercontent.com/assets/401965/22264644/0be88aba-e279-11e6-817e-90c20a5a18bc.png)![default_fence_junglewood](https://cloud.githubusercontent.com/assets/401965/22264645/0c03d5cc-e279-11e6-9f06-3fe0a0db1ce3.png)![default_fence_pine_wood](https://cloud.githubusercontent.com/assets/401965/22264647/0cb104fe-e279-11e6-88ac-da30024ff732.png)
![default_aspen_wood](https://cloud.githubusercontent.com/assets/401965/22264688/2efbb1da-e279-11e6-86f9-715d2e2a47a8.png)![default_junglewood](https://cloud.githubusercontent.com/assets/401965/22264692/33d00ea4-e279-11e6-940d-abb8b1e0e66a.png)![default_pine_wood](https://cloud.githubusercontent.com/assets/401965/22264698/37553b8a-e279-11e6-8714-88d5226a9225.png)

**Comment by tobyplowy** [comment]
@lipki nice

**Comment by lipki** [comment]
yep ok
