### ISSUE TITLE
cactus

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#39]
![default_cactus_side](https://cloud.githubusercontent.com/assets/401965/20409800/30dd6a40-ad1b-11e6-9576-b08ed5d2ded2.png)![default_cactus_top](https://cloud.githubusercontent.com/assets/401965/20409799/30da52c4-ad1b-11e6-865c-4248c52505c5.png)

**Comment by lipki** [comment]
![default_cactus_side](https://cloud.githubusercontent.com/assets/401965/20413630/4df0201a-ad2e-11e6-87e9-7c7c65b1dc1f.png)![default_cactus_top](https://cloud.githubusercontent.com/assets/401965/20413631/4e1c54aa-ad2e-11e6-8a1a-cfee71d024e5.png)

**Comment by lipki** [comment]
![default_cactus_side](https://cloud.githubusercontent.com/assets/401965/20456317/dd3aa51e-ae74-11e6-8257-11fd8265a129.png)
![default_cactus_top](https://cloud.githubusercontent.com/assets/401965/20456318/dd3c567a-ae74-11e6-9297-18a3a3fc4150.png)

**Comment by tobyplowy** [comment]
@lipki i think this is done

**Comment by lipki** [comment]
yes
