### ISSUE TITLE
Support connected chests

### ISSUE THREAD

**Issue by lightonflux** [SummerFields/Minetest#4]
https://forum.minetest.net/viewtopic.php?f=9&t=10264#p156571

I hope it will be part of minetest_game in the future but ATM it is just a mod. :)

**Comment by lipki** [comment]
This is done :)
Thank you for the suggestion.

https://summerfields.github.io/official/index.html#Minetest

**Comment by lightonflux** [comment]
Wow, that was fast. Thanks for adding it.

Am 18. Februar 2015 16:47:22 MEZ, schrieb "Lepeltier kévin" <notifications@github.com>:
>This is done :)
>Thank you for the suggestion.
>
>https://summerfields.github.io/official/index.html#Minetest
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SummerFields/Minetest/issues/4#issuecomment-74886814

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
