### ISSUE TITLE
torch

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#41]
![default_torch_animated](https://cloud.githubusercontent.com/assets/401965/20409948/338fd156-ad1b-11e6-87ad-75050c5af3c2.png)![default_torch_on_ceiling_animated](https://cloud.githubusercontent.com/assets/401965/20409950/3392889c-ad1b-11e6-89ce-4b93cc680d8d.png)![default_torch_on_floor](https://cloud.githubusercontent.com/assets/401965/20409949/3392a34a-ad1b-11e6-8890-160facf606b7.png)![default_torch_on_floor_animated](https://cloud.githubusercontent.com/assets/401965/20409951/33996220-ad1b-11e6-8077-79140c96a38b.png)

**Comment by lipki** [comment]
![default_torch_animated](https://cloud.githubusercontent.com/assets/401965/20414192/850465ea-ad31-11e6-9641-fff305c3990d.png)![default_torch_on_ceiling_animated](https://cloud.githubusercontent.com/assets/401965/20414191/8503ee12-ad31-11e6-93fa-3e75e570b56a.png)![default_torch_on_floor](https://cloud.githubusercontent.com/assets/401965/20414193/850a7a70-ad31-11e6-92c1-3551e01b2612.png)![default_torch_on_floor_animated](https://cloud.githubusercontent.com/assets/401965/20414194/850d6794-ad31-11e6-961d-79321db6dc0b.png)

**Comment by tobyplowy** [comment]
@lipki 3D torches will be added to minetest soon mostlikly in 0.4.15 so we probbably 
 wownt need default_torch_animated.png and default_torch_on_ceiling_animated.png finaly 3D torches XD

**Comment by lipki** [comment]
that is good news.

**Comment by tobyplowy** [comment]
True

**Comment by tobyplowy** [comment]
@lipki 3d torches are officially added

**Comment by tobyplowy** [comment]
@lipki the wall and roof torch can be removed (we have 3d torches now)

**Comment by lipki** [comment]
Good riddance !
