### ISSUE TITLE
gui

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#42]
![gui_formbg](https://cloud.githubusercontent.com/assets/401965/20409959/33b9d17c-ad1b-11e6-9675-a7634a409813.png)![gui_furnace_arrow_bg](https://cloud.githubusercontent.com/assets/401965/20409958/33b99d2e-ad1b-11e6-8aca-f9defb4520ad.png)![gui_furnace_arrow_fg](https://cloud.githubusercontent.com/assets/401965/20409960/33ba627c-ad1b-11e6-8acf-45083b8b848d.png)![gui_hb_bg](https://cloud.githubusercontent.com/assets/401965/20409961/33bfb358-ad1b-11e6-9680-b11aa9a2b09b.png)![gui_hotbar](https://cloud.githubusercontent.com/assets/401965/20409963/33cadf30-ad1b-11e6-98cb-0c9a0a4b83d5.png)![gui_hotbar_selected](https://cloud.githubusercontent.com/assets/401965/20409962/33c8acba-ad1b-11e6-8b5d-c78aca4b8d91.png)
![creative_trash_icon](https://cloud.githubusercontent.com/assets/401965/20409744/113a421c-ad1b-11e6-898c-f6efce20ad2b.png)

**Comment by lipki** [comment]
![gui_formbg](https://cloud.githubusercontent.com/assets/401965/20456283/3456d378-ae74-11e6-91d5-a77f09ed38d1.png)
![gui_hotbar](https://cloud.githubusercontent.com/assets/401965/20456285/36709cb6-ae74-11e6-82af-e6f86bc28d6e.png)
![gui_hotbar_selected](https://cloud.githubusercontent.com/assets/401965/20456286/37b76b90-ae74-11e6-8762-2eeff2d4118d.png)

**Comment by tobyplowy** [comment]
@lipki i made this gui_formbg its not perfect but meh
![gui_formbg](https://cloud.githubusercontent.com/assets/16853304/20459290/feeaee2a-aebb-11e6-8185-e8d7dd1bf104.png)

**Comment by lipki** [comment]
yes, yes ... why not.

**Comment by tobyplowy** [comment]
@lipki is it Possible to make a wooden background, i tried but I couldn't find anything to fill up the middle

**Comment by lipki** [comment]
like this : https://github.com/SummerFields/Mod-TerraFirmaCraft/blob/master/assets/terrafirmacraft/textures/gui/gui_barrel.png
maybe

**Comment by tobyplowy** [comment]
@lipki Yes xactly Like That

**Comment by tobyplowy** [comment]
@lipki yes exactly like that but without the pieces of paper and buttons of course XD

**Comment by tobyplowy** [comment]
@lipki will you make it or Should I make it?

**Comment by lipki** [comment]
![feeaee2a-aebb-11e6-8185-e8d7dd1bf104](https://cloud.githubusercontent.com/assets/401965/20570830/68822ff6-b1a5-11e6-84bd-504975e4e0f1.png)

**Comment by tobyplowy** [comment]
@lipki Looks good :D

**Comment by lipki** [comment]
eu no !
![screenshot at 2016-11-27 03 03 12](https://cloud.githubusercontent.com/assets/401965/20645028/1ce302f4-b44e-11e6-9db5-be8aeb6519a8.png)

**Comment by lipki** [comment]
![gui_hotbar](https://cloud.githubusercontent.com/assets/401965/20645062/d062b562-b44f-11e6-9a3b-c84c96a62001.png)

**Comment by tobyplowy** [comment]
@lipki What do you mean with eu no !

**Comment by lipki** [comment]
I mean, it's not legible, so we do not keep it.

**Comment by tobyplowy** [comment]
@lipki yeh Maybe

**Comment by lipki** [comment]
![creative_trash_icon](https://cloud.githubusercontent.com/assets/401965/20976800/f7cd6f0a-bca3-11e6-8e62-6d25dfc14880.png)

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by lipki** [comment]
![gui_furnace_arrow_bg](https://cloud.githubusercontent.com/assets/401965/22267726/38b5326c-e285-11e6-9580-745e0b38d95d.png)![gui_furnace_arrow_fg](https://cloud.githubusercontent.com/assets/401965/22267728/38b99366-e285-11e6-9127-b22ebf751222.png)![gui_hb_bg](https://cloud.githubusercontent.com/assets/401965/22267727/38b69fbc-e285-11e6-92eb-5f8c7de40d93.png)

**Comment by tobyplowy** [comment]
@lipki what is that? (Is it the furnace cooking animation?)

**Comment by lipki** [comment]
yep

**Comment by lipki** [comment]
Give me your advice please.

**Comment by tobyplowy** [comment]
@lipki in want?

**Comment by tobyplowy** [comment]
@lipki Yes it's good
