### ISSUE TITLE
character

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#43]
![character](https://cloud.githubusercontent.com/assets/401965/20409780/307f4672-ad1b-11e6-983c-aa2f0ab23f68.png)
![player](https://cloud.githubusercontent.com/assets/401965/20409966/33d77862-ad1b-11e6-9935-c68786d64efa.png)![player_back](https://cloud.githubusercontent.com/assets/401965/20409965/33d6c034-ad1b-11e6-9bf7-6db827c15107.png)
![wieldhand](https://cloud.githubusercontent.com/assets/401965/20409967/33dbd4fc-ad1b-11e6-9ea0-318491044472.png)

**Comment by lipki** [comment]
![character](https://cloud.githubusercontent.com/assets/401965/20413514/b0c68ec8-ad2d-11e6-9f2a-96d02b4f7ad2.png)
![player](https://cloud.githubusercontent.com/assets/401965/20413517/b58ede56-ad2d-11e6-806b-0ed149ee05a6.png)![player_back](https://cloud.githubusercontent.com/assets/401965/20413518/b5ba2a7a-ad2d-11e6-9728-54d314d2fbe2.png)
![wieldhand](https://cloud.githubusercontent.com/assets/401965/20413521/bdde95ec-ad2d-11e6-9dd6-484bf878f03a.png)

**Comment by tobyplowy** [comment]
@lipki This is done

**Comment by tobyplowy** [comment]
@lipki done?
