### ISSUE TITLE
boat

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#45]
![boats_inventory](https://cloud.githubusercontent.com/assets/401965/20409669/c700d8d2-ad1a-11e6-99cc-697803828cb1.png)![boats_wield](https://cloud.githubusercontent.com/assets/401965/20409668/c7004160-ad1a-11e6-9ff0-6ff0065b3e78.png)

**Comment by lipki** [comment]
![boats_inventory](https://cloud.githubusercontent.com/assets/401965/20413464/798e3744-ad2d-11e6-954c-7cb413d9843c.png)![boats_wield](https://cloud.githubusercontent.com/assets/401965/20413465/7993cff6-ad2d-11e6-8693-9dd0a21aa4fc.png)

**Comment by lipki** [comment]
We have to redo the item

**Comment by tobyplowy** [comment]
@lipki yeh but I'm not so good at 3d :/

**Comment by lipki** [comment]
I'm not sure, the raft is ugly in 3d, and even more in 2d.
The advantage of the summerfields item is that we understand what it is.

**Comment by lipki** [comment]
![boats_inventory](https://cloud.githubusercontent.com/assets/401965/22298563/45536f24-e321-11e6-8fed-019b12ef4e6c.png)
![boats_wield](https://cloud.githubusercontent.com/assets/401965/22298564/458132b0-e321-11e6-9a54-b8bc97ff6e37.png)

**Comment by tobyplowy** [comment]
@lipki nice (how do you make these do you have some kind of trick to do 3d pixel art?)

Also this is done yes

**Comment by lipki** [comment]
The 3d .blend file used by minetest, and the native format of blender, software 3d opensource and free.
So I just opened the file, and added the texture.

**Comment by tobyplowy** [comment]
@lipki Aaahhh you did it like that

**Comment by tobyplowy** [comment]
@lipki Is this done?

**Comment by lipki** [comment]
yes

**Comment by tobyplowy** [comment]
@lipki I think that's all right? apart from the water and lava but we can't fix that
