### ISSUE TITLE
spawn chest

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#46]
![bones_bottom](https://cloud.githubusercontent.com/assets/401965/20409678/d1736c8a-ad1a-11e6-9f27-8114b780422c.png)![bones_front](https://cloud.githubusercontent.com/assets/401965/20409677/d172cb40-ad1a-11e6-8f53-b33af1981220.png)![bones_rear](https://cloud.githubusercontent.com/assets/401965/20409679/d177e80a-ad1a-11e6-8e67-a2afc7dc437c.png)![bones_side](https://cloud.githubusercontent.com/assets/401965/20409680/d17980b6-ad1a-11e6-9f93-0f62f173b6cc.png)![bones_top](https://cloud.githubusercontent.com/assets/401965/20409681/d17e2d28-ad1a-11e6-921f-cde142eb6275.png)

**Comment by lipki** [comment]
![bones_bottom](https://cloud.githubusercontent.com/assets/401965/20413475/84be01d0-ad2d-11e6-9c55-5f2240f5b0bf.png)![bones_front](https://cloud.githubusercontent.com/assets/401965/20413476/84e8747e-ad2d-11e6-99d1-c3ab8a0f4bfa.png)![bones_rear](https://cloud.githubusercontent.com/assets/401965/20413477/84eb8826-ad2d-11e6-966f-877b6eb85412.png)![bones_side](https://cloud.githubusercontent.com/assets/401965/20413478/84ef1fcc-ad2d-11e6-8563-be7bff73f47d.png)![bones_top](https://cloud.githubusercontent.com/assets/401965/20413481/861d5c4c-ad2d-11e6-9150-d82bbf11b5f8.png)

**Comment by tobyplowy** [comment]
This one is Done :)

**Comment by lipki** [comment]
![bones_top](https://cloud.githubusercontent.com/assets/401965/20644703/e5a0b7aa-b43e-11e6-9638-c82e40b33214.png)

**Comment by tobyplowy** [comment]
@lipki Sorry For The Lack of work I promise you I will come back pretty soon 

Also is this Done?

**Comment by lipki** [comment]
https://github.com/SummerFields/Minetest/commit/eb585c3f61c0edc93231f2852f16ae2cfe47099b
