### ISSUE TITLE
doors

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#48]
![doors_blank](https://cloud.githubusercontent.com/assets/401965/20410351/df812252-ad1c-11e6-8e0b-f248685be3bb.png)
![doors_item_glass](https://cloud.githubusercontent.com/assets/401965/20410355/df88226e-ad1c-11e6-844a-50c54533f2ae.png)![doors_door_glass](https://cloud.githubusercontent.com/assets/401965/20410352/df81d9fe-ad1c-11e6-8c25-fccc7c4d0968.png)
![doors_item_obsidian_glass](https://cloud.githubusercontent.com/assets/401965/20410357/df9ba62c-ad1c-11e6-859f-2e3b2612d176.png)![doors_door_obsidian_glass](https://cloud.githubusercontent.com/assets/401965/20410354/df877b2a-ad1c-11e6-8d3f-abad0f175348.png)
![doors_item_wood](https://cloud.githubusercontent.com/assets/401965/20410362/dfaa21ac-ad1c-11e6-8c33-b75a990679ec.png)![doors_door_wood](https://cloud.githubusercontent.com/assets/401965/20410356/df8afa02-ad1c-11e6-853f-6d8ee5c8117d.png)![doors_trapdoor](https://cloud.githubusercontent.com/assets/401965/20410359/dfa88e82-ad1c-11e6-963f-b2a3cf08603a.png)![doors_trapdoor_side](https://cloud.githubusercontent.com/assets/401965/20410361/dfa9aa88-ad1c-11e6-8fab-090f69e88c8d.png)
![doors_item_steel](https://cloud.githubusercontent.com/assets/401965/20410358/df9f510a-ad1c-11e6-9a98-69a95229b647.png)![doors_door_steel](https://cloud.githubusercontent.com/assets/401965/20410353/df831d78-ad1c-11e6-9636-9c992e4ea641.png)![doors_trapdoor_steel](https://cloud.githubusercontent.com/assets/401965/20410360/dfa99d5e-ad1c-11e6-8747-e6bfac60c34f.png)![doors_trapdoor_steel_side](https://cloud.githubusercontent.com/assets/401965/20410363/dfb42ca6-ad1c-11e6-9224-4e7862374441.png)

**Comment by lipki** [comment]
![doors_item_glass](https://cloud.githubusercontent.com/assets/401965/20414103/1b6eaef6-ad31-11e6-830e-62a66fd1ab0d.png)![doors_door_glass](https://cloud.githubusercontent.com/assets/401965/20414104/1d7735f6-ad31-11e6-84e0-6fb4074084c4.png)
![doors_item_obsidian_glass](https://cloud.githubusercontent.com/assets/401965/20414109/221fc078-ad31-11e6-9876-e4b3a1919f94.png)![doors_door_obsidian_glass](https://cloud.githubusercontent.com/assets/401965/20414111/233ad7e0-ad31-11e6-8306-6d4b7342d854.png)
![doors_item_wood](https://cloud.githubusercontent.com/assets/401965/20414115/26d7dd30-ad31-11e6-9c9b-e116a73edc88.png)![doors_door_wood](https://cloud.githubusercontent.com/assets/401965/20414116/27f1a764-ad31-11e6-8fa8-fded31f41895.png)![doors_trapdoor](https://cloud.githubusercontent.com/assets/401965/20414125/335a8e0e-ad31-11e6-90bf-53b259f091d0.png)![doors_trapdoor_side](https://cloud.githubusercontent.com/assets/401965/20414128/359960c8-ad31-11e6-9735-b2b423198cbd.png)
![doors_item_steel](https://cloud.githubusercontent.com/assets/401965/20414118/2ba56ca6-ad31-11e6-94db-8723606c0fef.png)![doors_door_steel](https://cloud.githubusercontent.com/assets/401965/20414120/2cf6244c-ad31-11e6-8f2a-35ee643aeb05.png)![doors_trapdoor_steel](https://cloud.githubusercontent.com/assets/401965/20414133/3bca803a-ad31-11e6-9b6e-908bb10225d7.png)![doors_trapdoor_steel_side](https://cloud.githubusercontent.com/assets/401965/20414135/3cd484f8-ad31-11e6-9b45-fb85be7eda6e.png)

**Comment by lipki** [comment]
@tobyplowy 
![doors_door_obsidian_glass](https://cloud.githubusercontent.com/assets/16853304/20041482/f37096d2-a469-11e6-8a3a-857f80bff136.png)
![doors_door_glass](https://cloud.githubusercontent.com/assets/16853304/20041483/f3848340-a469-11e6-88da-65a0c4d5eb33.png)

**Comment by tobyplowy** [comment]
@lipki check The iron door you forgot to remove the window from the previous Image

**Comment by lipki** [comment]
![doors_door_steel](https://cloud.githubusercontent.com/assets/401965/20449430/86db1b12-ade9-11e6-88ff-d09d67d413b6.png)

**Comment by tobyplowy** [comment]
Lipki I think this is done

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by lipki** [comment]
yes
