### ISSUE TITLE
dye

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#49]
![dye_black](https://cloud.githubusercontent.com/assets/401965/20411390/99aa6ae0-ad21-11e6-8c51-e6d58754505a.png)![dye_blue](https://cloud.githubusercontent.com/assets/401965/20411391/99b0d13c-ad21-11e6-8093-28c197b10f1e.png)![dye_brown](https://cloud.githubusercontent.com/assets/401965/20411393/99b37770-ad21-11e6-87fe-d5e8ba0aa3ac.png)![dye_cyan](https://cloud.githubusercontent.com/assets/401965/20411392/99b37fae-ad21-11e6-8a58-e7ddd6a2948a.png)![dye_dark_green](https://cloud.githubusercontent.com/assets/401965/20411394/99b64e6e-ad21-11e6-8265-0ea29bbd3bac.png)![dye_dark_grey](https://cloud.githubusercontent.com/assets/401965/20411395/99bdc90a-ad21-11e6-9a1c-7f9024411ac6.png)![dye_green](https://cloud.githubusercontent.com/assets/401965/20411396/99c3b554-ad21-11e6-9751-f7c09bda4a29.png)![dye_grey](https://cloud.githubusercontent.com/assets/401965/20411397/99cd8976-ad21-11e6-9149-ab5287cae2ae.png)![dye_magenta](https://cloud.githubusercontent.com/assets/401965/20411399/99d007fa-ad21-11e6-99fa-f69f11cfc677.png)![dye_orange](https://cloud.githubusercontent.com/assets/401965/20411398/99cf20c4-ad21-11e6-8a46-963217bcea66.png)![dye_pink](https://cloud.githubusercontent.com/assets/401965/20411400/99d2a6d6-ad21-11e6-9d60-28e11b512713.png)![dye_red](https://cloud.githubusercontent.com/assets/401965/20411401/99d9054e-ad21-11e6-8ecd-c54ef07a6069.png)![dye_violet](https://cloud.githubusercontent.com/assets/401965/20411402/99e10b2c-ad21-11e6-95c4-416489268503.png)![dye_white](https://cloud.githubusercontent.com/assets/401965/20411403/99eb2d32-ad21-11e6-93bf-bb8f79aa02d5.png)![dye_yellow](https://cloud.githubusercontent.com/assets/401965/20411404/99ecdbb4-ad21-11e6-8954-a829a2cc8270.png)

**Comment by lipki** [comment]
![dye_black](https://cloud.githubusercontent.com/assets/401965/20413852/86e05362-ad2f-11e6-9aa9-d7b20dea76ef.png)![dye_blue](https://cloud.githubusercontent.com/assets/401965/20413853/870c1c72-ad2f-11e6-82f1-632e2fb97cfc.png)![dye_brown](https://cloud.githubusercontent.com/assets/401965/20413854/870d4a70-ad2f-11e6-9f7a-97904263adf9.png)![dye_cyan](https://cloud.githubusercontent.com/assets/401965/20413855/89a06c5e-ad2f-11e6-9324-0d96d365e0dc.png)![dye_dark_green](https://cloud.githubusercontent.com/assets/401965/20413858/89a7a0be-ad2f-11e6-8275-9db3b0042473.png)![dye_dark_grey](https://cloud.githubusercontent.com/assets/401965/20413856/89a6bf50-ad2f-11e6-9b05-44b08c4ea64a.png)![dye_green](https://cloud.githubusercontent.com/assets/401965/20413857/89a6ea3e-ad2f-11e6-95c8-465bdd75fd43.png)![dye_grey](https://cloud.githubusercontent.com/assets/401965/20413859/89baa376-ad2f-11e6-9934-5b51c74622f0.png)![dye_magenta](https://cloud.githubusercontent.com/assets/401965/20413863/89d8ce6e-ad2f-11e6-8e87-89ee59f2a185.png)![dye_orange](https://cloud.githubusercontent.com/assets/401965/20413864/89da217e-ad2f-11e6-9c0b-4b78e0a37d01.png)![dye_pink](https://cloud.githubusercontent.com/assets/401965/20413860/89c2b868-ad2f-11e6-959b-87aed635f858.png)![dye_red](https://cloud.githubusercontent.com/assets/401965/20413862/89caeb78-ad2f-11e6-879b-983400d0aec0.png)![dye_violet](https://cloud.githubusercontent.com/assets/401965/20413861/89c86272-ad2f-11e6-9699-699c5c33c5fe.png)![dye_white](https://cloud.githubusercontent.com/assets/401965/20413867/8bbf703e-ad2f-11e6-9c58-16e411b5aa2f.png)![dye_yellow](https://cloud.githubusercontent.com/assets/401965/20413868/8bc15462-ad2f-11e6-9981-b5d63bcee802.png)

**Comment by tobyplowy** [comment]
@lipki looks good close?

**Comment by lipki** [comment]
![dye_white](https://cloud.githubusercontent.com/assets/401965/20456278/09206b7e-ae74-11e6-8462-9dcf57017339.png)
