### ISSUE TITLE
wheat

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#50]
![farming_wheat_seed](https://cloud.githubusercontent.com/assets/401965/20411605/6672fd12-ad22-11e6-86d5-d97bf5846bee.png)![farming_wheat_1](https://cloud.githubusercontent.com/assets/401965/20411597/663d30b0-ad22-11e6-8ba7-980d79a2d9c7.png)![farming_wheat_2](https://cloud.githubusercontent.com/assets/401965/20411598/664d3190-ad22-11e6-802e-2f7924e7266d.png)![farming_wheat_3](https://cloud.githubusercontent.com/assets/401965/20411599/66522e66-ad22-11e6-85a1-18215d014270.png)![farming_wheat_4](https://cloud.githubusercontent.com/assets/401965/20411600/665586ec-ad22-11e6-80eb-6944a7b30d20.png)![farming_wheat_5](https://cloud.githubusercontent.com/assets/401965/20411603/665ff58c-ad22-11e6-8fd3-e5b0f3d8f643.png)![farming_wheat_6](https://cloud.githubusercontent.com/assets/401965/20411602/665f14d2-ad22-11e6-9719-d50e6e2872d8.png)![farming_wheat_7](https://cloud.githubusercontent.com/assets/401965/20411601/665e5d94-ad22-11e6-8cc3-6cd900fb703a.png)![farming_wheat_8](https://cloud.githubusercontent.com/assets/401965/20411604/666b5512-ad22-11e6-9fcb-6edec16de4ff.png)![farming_wheat](https://cloud.githubusercontent.com/assets/401965/20411596/663cf97e-ad22-11e6-8a9e-087f7e30bbed.png)![farming_straw](https://cloud.githubusercontent.com/assets/401965/20411590/661bff58-ad22-11e6-830c-f89f43306335.png)![farming_flour](https://cloud.githubusercontent.com/assets/401965/20411584/66029c3e-ad22-11e6-8e43-0e9412d8940b.png)![farming_bread](https://cloud.githubusercontent.com/assets/401965/20411570/65b60d10-ad22-11e6-9012-fbd9ba2a2b3a.png)

**Comment by lipki** [comment]
![farming_wheat_seed](https://cloud.githubusercontent.com/assets/401965/20414066/ef1dc6de-ad30-11e6-8507-cc5e2150805c.png)![farming_wheat_1](https://cloud.githubusercontent.com/assets/401965/20414067/f1133fe6-ad30-11e6-8940-162299624573.png)![farming_wheat_2](https://cloud.githubusercontent.com/assets/401965/20414068/f13e7440-ad30-11e6-9248-303248e6488e.png)![farming_wheat_3](https://cloud.githubusercontent.com/assets/401965/20414069/f140743e-ad30-11e6-95ef-5d7574556902.png)![farming_wheat_4](https://cloud.githubusercontent.com/assets/401965/20414070/f14639c8-ad30-11e6-9b45-8e774065388d.png)![farming_wheat_5](https://cloud.githubusercontent.com/assets/401965/20414074/f30a2b16-ad30-11e6-8384-811d5697d943.png)![farming_wheat_6](https://cloud.githubusercontent.com/assets/401965/20414075/f30d1db2-ad30-11e6-9fc9-9f87dddbc9d4.png)![farming_wheat_7](https://cloud.githubusercontent.com/assets/401965/20414076/f31345ac-ad30-11e6-8218-e4059e87e583.png)![farming_wheat_8](https://cloud.githubusercontent.com/assets/401965/20414077/f3142968-ad30-11e6-9f0c-8cef53be6f1b.png)![farming_wheat](https://cloud.githubusercontent.com/assets/401965/20414078/f45ad98e-ad30-11e6-9a8d-823537b75792.png)![farming_straw](https://cloud.githubusercontent.com/assets/401965/20414081/f6b88d0c-ad30-11e6-9108-eafa3d41fc2a.png)![farming_flour](https://cloud.githubusercontent.com/assets/401965/20414084/f908e6f6-ad30-11e6-82bc-d44706d17097.png)![farming_bread](https://cloud.githubusercontent.com/assets/401965/20414086/fa8b0d2e-ad30-11e6-8d36-2ce3cfe9b751.png)

**Comment by lipki** [comment]
by @tobyplowy 
maby a new farming_straw
farming_straw

**Comment by tobyplowy** [comment]
@lipki done

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by lipki** [comment]
yep
