### ISSUE TITLE
cotton

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#51]
![farming_cotton_seed](https://cloud.githubusercontent.com/assets/401965/20411579/65e6da08-ad22-11e6-9ec1-9a9603963166.png)![farming_cotton_1](https://cloud.githubusercontent.com/assets/401965/20411571/65ba9c2c-ad22-11e6-8443-413073ffbaaa.png)![farming_cotton_2](https://cloud.githubusercontent.com/assets/401965/20411573/65c01242-ad22-11e6-9023-6514ce4295ef.png)![farming_cotton_3](https://cloud.githubusercontent.com/assets/401965/20411574/65c6f1e8-ad22-11e6-8822-e55d20b575f4.png)![farming_cotton_4](https://cloud.githubusercontent.com/assets/401965/20411575/65c82b3a-ad22-11e6-8253-f5b7ffad0ab3.png)![farming_cotton_5](https://cloud.githubusercontent.com/assets/401965/20411576/65d909c8-ad22-11e6-94c4-bb7f58efedbe.png)![farming_cotton_6](https://cloud.githubusercontent.com/assets/401965/20411577/65dd2ca6-ad22-11e6-9e48-004fe428d928.png)![farming_cotton_7](https://cloud.githubusercontent.com/assets/401965/20411578/65e17dba-ad22-11e6-894f-854782a0cb95.png)![farming_cotton_8](https://cloud.githubusercontent.com/assets/401965/20411580/65e77c4c-ad22-11e6-9cd0-595dac9add46.png)![farming_cotton](https://cloud.githubusercontent.com/assets/401965/20411572/65bee2c8-ad22-11e6-8333-342b0f2772a4.png)

**Comment by lipki** [comment]
![farming_cotton_seed](https://cloud.githubusercontent.com/assets/401965/20413943/0264c0ea-ad30-11e6-9e3a-0e3a9939a6ee.png)![farming_cotton_1](https://cloud.githubusercontent.com/assets/401965/20413949/04d919f2-ad30-11e6-94a9-19d103eaabc1.png)![farming_cotton_2](https://cloud.githubusercontent.com/assets/401965/20413950/05002736-ad30-11e6-9ddf-0a554e0799e8.png)![farming_cotton_3](https://cloud.githubusercontent.com/assets/401965/20413951/05024002-ad30-11e6-98ce-66c7e99e6513.png)![farming_cotton_4](https://cloud.githubusercontent.com/assets/401965/20413952/06c21016-ad30-11e6-9df1-1c905ab2b107.png)![farming_cotton_5](https://cloud.githubusercontent.com/assets/401965/20413954/06c5a15e-ad30-11e6-838a-ca4f8a5d8d6b.png)![farming_cotton_6](https://cloud.githubusercontent.com/assets/401965/20413953/06c35e26-ad30-11e6-9786-dc53132ebe63.png)![farming_cotton_7](https://cloud.githubusercontent.com/assets/401965/20413955/06c665f8-ad30-11e6-96e3-53f84f895f6f.png)![farming_cotton_8](https://cloud.githubusercontent.com/assets/401965/20413956/06db0986-ad30-11e6-8df0-1ff1524ce6e2.png)![farming_cotton](https://cloud.githubusercontent.com/assets/401965/20413958/087debe6-ad30-11e6-9804-21b4aefbf05b.png)

**Comment by tobyplowy** [comment]
@lipki this is good

**Comment by tobyplowy** [comment]
@lipki done?
