### ISSUE TITLE
Flowers

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#53]
![flowers_dandelion_white](https://cloud.githubusercontent.com/assets/401965/20411672/cada9c10-ad22-11e6-9176-cf10ece2373b.png)![flowers_dandelion_yellow](https://cloud.githubusercontent.com/assets/401965/20411674/cae19b1e-ad22-11e6-812d-ad8f07bafb33.png)![flowers_geranium](https://cloud.githubusercontent.com/assets/401965/20411673/cae0a218-ad22-11e6-9397-8b1c7512d9f9.png)![flowers_rose](https://cloud.githubusercontent.com/assets/401965/20411677/caea9a02-ad22-11e6-952b-6b957a4efd62.png)![flowers_tulip](https://cloud.githubusercontent.com/assets/401965/20411678/caf3a66a-ad22-11e6-9388-483c7d509c2a.png)![flowers_viola](https://cloud.githubusercontent.com/assets/401965/20411680/cb01ece8-ad22-11e6-996e-1769962419aa.png)
![flowers_waterlily](https://cloud.githubusercontent.com/assets/401965/20411679/caffc224-ad22-11e6-9752-2b2d51253c73.png)
![flowers_mushroom_brown](https://cloud.githubusercontent.com/assets/401965/20411675/cae349c8-ad22-11e6-8993-816b356f8bb7.png)![flowers_mushroom_red](https://cloud.githubusercontent.com/assets/401965/20411676/cae84176-ad22-11e6-931c-84a4eec393b3.png)
![default_papyrus](https://cloud.githubusercontent.com/assets/401965/20409895/32a039de-ad1b-11e6-926d-3d9b942cf8cc.png)
![default_apple](https://cloud.githubusercontent.com/assets/401965/20409785/30986346-ad1b-11e6-9871-c8b74e5f67f3.png)

**Comment by lipki** [comment]
![flowers_dandelion_white](https://cloud.githubusercontent.com/assets/401965/20413548/e04549aa-ad2d-11e6-87e7-ea2d882d6b32.png)![flowers_dandelion_yellow](https://cloud.githubusercontent.com/assets/401965/20413552/e340d3b8-ad2d-11e6-9bdd-c8b8b5a4e039.png)![flowers_geranium](https://cloud.githubusercontent.com/assets/401965/20413553/e369b29c-ad2d-11e6-8491-da64d3a90f80.png)![flowers_rose](https://cloud.githubusercontent.com/assets/401965/20413554/e4ab9c38-ad2d-11e6-8411-22f9832a457c.png)![flowers_tulip](https://cloud.githubusercontent.com/assets/401965/20413555/e6b7b034-ad2d-11e6-937c-57a88715d5d3.png)![flowers_viola](https://cloud.githubusercontent.com/assets/401965/20413556/e6ba4fc4-ad2d-11e6-8dfb-2cb0cdd410d8.png)
![flowers_waterlily](https://cloud.githubusercontent.com/assets/401965/20413566/f1bcbe3e-ad2d-11e6-855d-f01861835443.png)
![flowers_mushroom_brown](https://cloud.githubusercontent.com/assets/401965/20413571/f84a30e2-ad2d-11e6-9165-423c9fb29127.png)![flowers_mushroom_red](https://cloud.githubusercontent.com/assets/401965/20413572/f8718610-ad2d-11e6-8044-6d8d04887bec.png)
![default_papyrus](https://cloud.githubusercontent.com/assets/401965/20413593/0d2772a4-ad2e-11e6-98cc-19c9703d5ea0.png)
![default_apple](https://cloud.githubusercontent.com/assets/401965/20413595/13dfccb8-ad2e-11e6-966e-3d3557fbaaa1.png)

**Comment by tobyplowy** [comment]
Add my new oxy dasi texture

**Comment by lipki** [comment]
![flower_oxeye_daisy](https://cloud.githubusercontent.com/assets/401965/20449311/ce7c0054-ade8-11e6-9bba-473691fd6741.png)

**Comment by tobyplowy** [comment]
@lipki I think you need to use the tulip from the Minecraft version

**Comment by lipki** [comment]
it's the case.

**Comment by tobyplowy** [comment]
@lipki OK well I guess this is done then
