### ISSUE TITLE
Rail

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#54]
![default_rail](https://cloud.githubusercontent.com/assets/401965/20409901/32bc8a12-ad1b-11e6-885c-56e27ce63af7.png)![default_rail_crossing](https://cloud.githubusercontent.com/assets/401965/20409902/32c80554-ad1b-11e6-8952-eba001e1ba72.png)![default_rail_curved](https://cloud.githubusercontent.com/assets/401965/20409903/32cdbeea-ad1b-11e6-8179-8536a530a889.png)![default_rail_t_junction](https://cloud.githubusercontent.com/assets/401965/20409905/32d01e6a-ad1b-11e6-8794-f82bce933c6a.png)

**Comment by lipki** [comment]
![default_rail](https://cloud.githubusercontent.com/assets/401965/20413916/d8db2584-ad2f-11e6-9cc6-4e0b0e276077.png)![default_rail_crossing](https://cloud.githubusercontent.com/assets/401965/20413919/d9095d28-ad2f-11e6-87ef-9c7d7b228e13.png)![default_rail_curved](https://cloud.githubusercontent.com/assets/401965/20413920/d90976a0-ad2f-11e6-8403-060c1dc012d7.png)![default_rail_t_junction](https://cloud.githubusercontent.com/assets/401965/20413921/d90f4580-ad2f-11e6-8250-d3fd50f5aaf8.png)

**Comment by tobyplowy** [comment]
@lipki Looks good

**Comment by tobyplowy** [comment]
@lipki they will be added to default minetest game 0.4.15 but with difrent names

**Comment by lipki** [comment]
Yes I corrected that yesterday.
 ps : I will not be available for a week.

**Comment by tobyplowy** [comment]
@lipki thats ok sorry for asking But can i know What you're going to do?

**Comment by lipki** [comment]
:D 
I will answer you without any problem.
If it was a private conversation.
This is a public conversation.
We can not talk about anything and everything.

**Comment by tobyplowy** [comment]
@lipki I see what you mean ( ͡° ͜ʖ ͡°)

**Comment by lipki** [comment]
https://github.com/SummerFields/Minetest/commit/be73888f0c86e4587ab4fd000a16927e43267aee
