### ISSUE TITLE
book

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#55]
![default_book](https://cloud.githubusercontent.com/assets/401965/20409793/30bc3e60-ad1b-11e6-88b4-d179b17ecd7f.png)![default_bookshelf](https://cloud.githubusercontent.com/assets/401965/20409794/30c24df0-ad1b-11e6-94d7-214b183e2b28.png)![default_book_written](https://cloud.githubusercontent.com/assets/401965/20409795/30c41c48-ad1b-11e6-8866-714d2fed7b70.png)![default_paper](https://cloud.githubusercontent.com/assets/401965/20409894/329ec5e0-ad1b-11e6-9de7-c3fdef61b8d0.png)

**Comment by lipki** [comment]
![default_book](https://cloud.githubusercontent.com/assets/401965/20413648/6468d2e2-ad2e-11e6-8804-7219a21bf6b6.png)![default_bookshelf](https://cloud.githubusercontent.com/assets/401965/20413649/659bb6fc-ad2e-11e6-895e-3f0b7169b6cc.png)![default_book_written](https://cloud.githubusercontent.com/assets/401965/20413651/671a6500-ad2e-11e6-9d6d-603c73beec88.png)![default_paper](https://cloud.githubusercontent.com/assets/401965/20413656/6dac3768-ad2e-11e6-9875-3ec1dad5747d.png)

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by lipki** [comment]
yep
