### ISSUE TITLE
wool

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#56]
![wool_black](https://cloud.githubusercontent.com/assets/401965/20411800/75564c3e-ad23-11e6-8ed2-56f5b3abd19c.png)![wool_blue](https://cloud.githubusercontent.com/assets/401965/20411801/75598110-ad23-11e6-9e17-4fc52651343d.png)![wool_brown](https://cloud.githubusercontent.com/assets/401965/20411803/7560fabc-ad23-11e6-96ed-2ad34dfd4cdd.png)![wool_cyan](https://cloud.githubusercontent.com/assets/401965/20411802/755e9f7e-ad23-11e6-9dda-65ddc4772de5.png)![wool_dark_green](https://cloud.githubusercontent.com/assets/401965/20411804/75700048-ad23-11e6-91bd-10a8b005a1c4.png)![wool_dark_grey](https://cloud.githubusercontent.com/assets/401965/20411805/7571360c-ad23-11e6-9b77-982006c25e5a.png)![wool_green](https://cloud.githubusercontent.com/assets/401965/20411806/75754ef4-ad23-11e6-94ec-a2acfd820b82.png)![wool_grey](https://cloud.githubusercontent.com/assets/401965/20411808/757a3a86-ad23-11e6-9fa5-2f4ee86d4d58.png)![wool_magenta](https://cloud.githubusercontent.com/assets/401965/20411807/7579a40e-ad23-11e6-8e0b-d961f0e4dcbd.png)![wool_orange](https://cloud.githubusercontent.com/assets/401965/20411809/757d078e-ad23-11e6-81af-834c803f9b03.png)![wool_pink](https://cloud.githubusercontent.com/assets/401965/20411810/7591d7a4-ad23-11e6-8b61-384e4f9ba16f.png)![wool_red](https://cloud.githubusercontent.com/assets/401965/20411811/75941f1e-ad23-11e6-83a3-68ae11e11577.png)![wool_violet](https://cloud.githubusercontent.com/assets/401965/20411812/7599a6aa-ad23-11e6-8df6-a4aff3625082.png)![wool_white](https://cloud.githubusercontent.com/assets/401965/20411813/759a9bd2-ad23-11e6-83f3-8591a2d5613f.png)![wool_yellow](https://cloud.githubusercontent.com/assets/401965/20411814/759c8942-ad23-11e6-8c99-4df9105072fb.png)

**Comment by lipki** [comment]
![wool_black](https://cloud.githubusercontent.com/assets/401965/20413309/98a49ab6-ad2c-11e6-8f65-03160339de37.png)![wool_blue](https://cloud.githubusercontent.com/assets/401965/20413310/98ca0224-ad2c-11e6-986d-b3e77956e38f.png)![wool_brown](https://cloud.githubusercontent.com/assets/401965/20413313/9c062d1e-ad2c-11e6-82ed-85e565bc28b6.png)![wool_cyan](https://cloud.githubusercontent.com/assets/401965/20413314/9c08bc1e-ad2c-11e6-9857-77342f09a15c.png)![wool_dark_green](https://cloud.githubusercontent.com/assets/401965/20413315/9c343574-ad2c-11e6-9f09-dd588450ed56.png)![wool_dark_grey](https://cloud.githubusercontent.com/assets/401965/20413316/9c3556b6-ad2c-11e6-8fe2-c0368fd38ce3.png)![wool_green](https://cloud.githubusercontent.com/assets/401965/20413317/9c3693e6-ad2c-11e6-976c-a91b64aacd6b.png)![wool_grey](https://cloud.githubusercontent.com/assets/401965/20413320/9fb10dee-ad2c-11e6-89e1-953ea7c55516.png)![wool_magenta](https://cloud.githubusercontent.com/assets/401965/20413321/9fb5d342-ad2c-11e6-9cec-3475a89d7efd.png)![wool_orange](https://cloud.githubusercontent.com/assets/401965/20413322/9fb6d44a-ad2c-11e6-8a6f-5e9db851feda.png)![wool_pink](https://cloud.githubusercontent.com/assets/401965/20413323/9fb77c9c-ad2c-11e6-9dbe-b0ae4b6b098e.png)![wool_red](https://cloud.githubusercontent.com/assets/401965/20413324/9fb97f1a-ad2c-11e6-9c0a-56704fe5d810.png)![wool_violet](https://cloud.githubusercontent.com/assets/401965/20413330/a2f81e8e-ad2c-11e6-8c3d-baf812f361f7.png)![wool_white](https://cloud.githubusercontent.com/assets/401965/20413331/a2fbea5a-ad2c-11e6-8dc9-6a2cfc49db02.png)![wool_yellow](https://cloud.githubusercontent.com/assets/401965/20413332/a3011444-ad2c-11e6-8fc3-9434dc233b6c.png)

**Comment by tobyplowy** [comment]
@lipki done? or do we make the colors more acurate to the original minetest textures?

**Comment by tobyplowy** [comment]
@lipki Is this done

**Comment by lipki** [comment]
yep
