### ISSUE TITLE
Glass

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#57]
![xpanes_grey](https://cloud.githubusercontent.com/assets/401965/20411834/8d9c2318-ad23-11e6-9c16-e51f9b9cde04.png)![xpanes_pane_half](https://cloud.githubusercontent.com/assets/401965/20411836/8da2757e-ad23-11e6-9e09-f12daea6e85f.png)![xpanes_space](https://cloud.githubusercontent.com/assets/401965/20411835/8da1360a-ad23-11e6-937d-4b8d4bca9032.png)![xpanes_white](https://cloud.githubusercontent.com/assets/401965/20411837/8da3dd88-ad23-11e6-97e8-bae8a5517ce1.png)

![default_glass](https://cloud.githubusercontent.com/assets/401965/20409845/31be4362-ad1b-11e6-9c96-29f4d622cd8b.png)![default_glass_detail](https://cloud.githubusercontent.com/assets/401965/20409846/31c6a570-ad1b-11e6-866e-4beeff438c5f.png)

![vessels_drinking_glass](https://cloud.githubusercontent.com/assets/401965/20411782/5ccc5dfc-ad23-11e6-8960-516f214aaf9c.png)![vessels_drinking_glass_inv](https://cloud.githubusercontent.com/assets/401965/20411781/5cc59c7e-ad23-11e6-98eb-82a79aa525a9.png)![vessels_glass_bottle](https://cloud.githubusercontent.com/assets/401965/20411783/5ccfde1e-ad23-11e6-99a2-7d3ba6b4c412.png)![vessels_glass_bottle_inv](https://cloud.githubusercontent.com/assets/401965/20411786/5cdb909c-ad23-11e6-9bc3-738b2e582e1f.png)![vessels_glass_fragments](https://cloud.githubusercontent.com/assets/401965/20411785/5cd4299c-ad23-11e6-9efd-b4c41843f0c2.png)
![vessels_shelf](https://cloud.githubusercontent.com/assets/401965/20411784/5cd32470-ad23-11e6-9c03-ce60e6faee29.png)

**Comment by lipki** [comment]
__![xpanes_pane_half](https://cloud.githubusercontent.com/assets/401965/20413363/e4cd1e7c-ad2c-11e6-8b90-e3869cd0385a.png)__![xpanes_white](https://cloud.githubusercontent.com/assets/401965/20413368/edb7eb16-ad2c-11e6-9d0f-e2471e25d2c3.png)_

![default_glass](https://cloud.githubusercontent.com/assets/401965/20414720/3aa6010e-ad34-11e6-8a48-993c44ecd1b4.png)![default_glass_detail](https://cloud.githubusercontent.com/assets/401965/20414721/3bfe584e-ad34-11e6-9d45-4e4d1041100a.png)

![vessels_drinking_glass](https://cloud.githubusercontent.com/assets/401965/20414722/415d4ac0-ad34-11e6-9097-bc8032562d8c.png)![vessels_drinking_glass_inv](https://cloud.githubusercontent.com/assets/401965/20414723/41858daa-ad34-11e6-8bd6-bdd6365a2bdd.png)![vessels_glass_bottle](https://cloud.githubusercontent.com/assets/401965/20414724/418b4c68-ad34-11e6-8b03-08794849f7e4.png)![vessels_glass_bottle_inv](https://cloud.githubusercontent.com/assets/401965/20414725/436bd73c-ad34-11e6-8cc4-5f11ede8db31.png)![vessels_glass_fragments](https://cloud.githubusercontent.com/assets/401965/20414726/436eb902-ad34-11e6-9bf5-db1b9a10f0bd.png)

**Comment by tobyplowy** [comment]
@lipki this is done yes?

**Comment by lipki** [comment]
yep
