### ISSUE TITLE
TNT

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#58]
![tnt_blast](https://cloud.githubusercontent.com/assets/401965/20411718/fdc064d4-ad22-11e6-83d7-396a8dcc9be7.png)
![tnt_boom](https://cloud.githubusercontent.com/assets/401965/20411719/fdc2fdf2-ad22-11e6-8a66-84fff7b11424.png)
![tnt_gunpowder_burning_crossing_animated](https://cloud.githubusercontent.com/assets/401965/20411721/fdc8af40-ad22-11e6-9782-d5fa06ed47f8.png)![tnt_gunpowder_burning_curved_animated](https://cloud.githubusercontent.com/assets/401965/20411722/fdcfc83e-ad22-11e6-9187-aaf8acb98f6f.png)![tnt_gunpowder_burning_straight_animated](https://cloud.githubusercontent.com/assets/401965/20411723/fdd165fe-ad22-11e6-8977-44784beea634.png)![tnt_gunpowder_burning_t_junction_animated](https://cloud.githubusercontent.com/assets/401965/20411724/fddb7c60-ad22-11e6-8c63-1ae5906dea63.png)
![tnt_gunpowder_crossing](https://cloud.githubusercontent.com/assets/401965/20411725/fddf0100-ad22-11e6-910d-c320bc8198ac.png)![tnt_gunpowder_curved](https://cloud.githubusercontent.com/assets/401965/20411726/fde440d4-ad22-11e6-84d3-4de008f59dc5.png)![tnt_gunpowder_straight](https://cloud.githubusercontent.com/assets/401965/20411728/fdeca2a6-ad22-11e6-8b9d-7330585c931e.png)![tnt_gunpowder_t_junction](https://cloud.githubusercontent.com/assets/401965/20411729/fdf0a234-ad22-11e6-981d-4e6ee344fa82.png)
![tnt_smoke](https://cloud.githubusercontent.com/assets/401965/20411731/fdffb972-ad22-11e6-810b-ede658799702.png)
![tnt_gunpowder_inventory](https://cloud.githubusercontent.com/assets/401965/20411727/fde53d86-ad22-11e6-99cd-891e0c2f1360.png)
![tnt_top](https://cloud.githubusercontent.com/assets/401965/20411732/fe01021e-ad22-11e6-8b98-74a95add08f4.png)![tnt_side](https://cloud.githubusercontent.com/assets/401965/20411730/fdf6f666-ad22-11e6-8826-983ce9a82ae6.png)![tnt_bottom](https://cloud.githubusercontent.com/assets/401965/20411720/fdc62d4c-ad22-11e6-9b72-fcc9eb9c4572.png)
![tnt_top_burning](https://cloud.githubusercontent.com/assets/401965/20411733/fe03be46-ad22-11e6-8d25-9be24f62ef90.png)![tnt_top_burning_animated](https://cloud.githubusercontent.com/assets/401965/20411734/fe097e44-ad22-11e6-89f3-8704b7cd4add.png)

**Comment by lipki** [comment]
![tnt_blast](https://cloud.githubusercontent.com/assets/401965/20413141/7ea7b9c8-ad2b-11e6-93d2-c048a4ad10b6.png)
![tnt_boom](https://cloud.githubusercontent.com/assets/401965/20413142/7fd8cd96-ad2b-11e6-9f88-a27f44f1583b.png)
![tnt_gunpowder_burning_crossing_animated](https://cloud.githubusercontent.com/assets/401965/20413147/894602fe-ad2b-11e6-81bf-26ee406b6c3f.png)![tnt_gunpowder_burning_curved_animated](https://cloud.githubusercontent.com/assets/401965/20413148/8b323e2a-ad2b-11e6-8213-3358f69d1084.png)![tnt_gunpowder_burning_straight_animated](https://cloud.githubusercontent.com/assets/401965/20413149/8c6b32c4-ad2b-11e6-8715-407eb14287b5.png)![tnt_gunpowder_burning_t_junction_animated](https://cloud.githubusercontent.com/assets/401965/20413151/8dc76fd4-ad2b-11e6-954b-2174c57ae3d8.png)
![tnt_gunpowder_crossing](https://cloud.githubusercontent.com/assets/401965/20413159/96a6d266-ad2b-11e6-8b7a-0d3f36efa0f1.png)![tnt_gunpowder_curved](https://cloud.githubusercontent.com/assets/401965/20413160/9872d3b0-ad2b-11e6-940f-ae938771ffd9.png)![tnt_gunpowder_straight](https://cloud.githubusercontent.com/assets/401965/20413162/9a71a24a-ad2b-11e6-8eeb-4858773ec45c.png)![tnt_gunpowder_t_junction](https://cloud.githubusercontent.com/assets/401965/20413166/9b9ecf26-ad2b-11e6-8419-1f2c7153e6d8.png)
![tnt_smoke](https://cloud.githubusercontent.com/assets/401965/20413174/a4510a4e-ad2b-11e6-9a37-23dab88e349c.png)
![tnt_top](https://cloud.githubusercontent.com/assets/401965/20413182/b055f5f2-ad2b-11e6-847a-d70b87d0d3d7.png)![tnt_side](https://cloud.githubusercontent.com/assets/401965/20413183/b299a5f2-ad2b-11e6-9588-f3153b7955a0.png)![tnt_bottom](https://cloud.githubusercontent.com/assets/401965/20413207/d38a33b2-ad2b-11e6-9e35-54f2e42c64ce.png)
![tnt_top_burning](https://cloud.githubusercontent.com/assets/401965/20413212/d6e74e46-ad2b-11e6-97db-9876ed974439.png)![tnt_top_burning_animated](https://cloud.githubusercontent.com/assets/401965/20413215/d88befae-ad2b-11e6-8caa-1b30b630ed0b.png)

**Comment by tobyplowy** [comment]
@lipki this is done
