### ISSUE TITLE
obsidian

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#59]
![default_obsidian](https://cloud.githubusercontent.com/assets/401965/20409889/3291a414-ad1b-11e6-87b8-54aacc935cf3.png)![default_obsidian_brick](https://cloud.githubusercontent.com/assets/401965/20409891/329404de-ad1b-11e6-9c67-f1a6414a0b41.png)![default_obsidian_glass](https://cloud.githubusercontent.com/assets/401965/20409890/3293abba-ad1b-11e6-9859-564f06055e7d.png)![default_obsidian_glass_detail](https://cloud.githubusercontent.com/assets/401965/20409893/3298bc36-ad1b-11e6-9800-80bb8dd2e919.png)![default_obsidian_shard](https://cloud.githubusercontent.com/assets/401965/20409892/3298cac8-ad1b-11e6-8823-30c50fbe553b.png)

**Comment by lipki** [comment]
![default_obsidian](https://cloud.githubusercontent.com/assets/401965/20413120/681e9fa0-ad2b-11e6-82a9-3c0bfcb41e8d.png)![default_obsidian_brick](https://cloud.githubusercontent.com/assets/401965/20413122/690e3b28-ad2b-11e6-93cc-dba603f7108c.png)![default_obsidian_glass](https://cloud.githubusercontent.com/assets/401965/20413125/6a86bb6a-ad2b-11e6-9188-960c7367523c.png)![default_obsidian_glass_detail](https://cloud.githubusercontent.com/assets/401965/20413130/6d96f37e-ad2b-11e6-9ad9-ce74d8b47de3.png)![default_obsidian_shard](https://cloud.githubusercontent.com/assets/401965/20413132/6ec3b430-ad2b-11e6-9196-436086d284cb.png)

**Comment by tobyplowy** [comment]
default_obsidian_shard.png needs to be redone

**Comment by lipki** [comment]
What is it that disturbs you?

**Comment by tobyplowy** [comment]
@lipki the texture looks a bit weird real obsidian has a more shiny feel rather than a stone feel
Maybe it can be redone and we can also redo the Minecraft one 

Same problem with coal I don't feel that It Looks like coal but More like Black Stone or something :)

**Comment by lipki** [comment]
![default_obsidian](https://cloud.githubusercontent.com/assets/401965/22270218/ddb2570a-e28e-11e6-9812-25ea0b827ffa.png)![default_obsidian_block](https://cloud.githubusercontent.com/assets/401965/22270219/ddb9a4f6-e28e-11e6-9f86-7e8ce85ee166.png)![default_obsidian_brick](https://cloud.githubusercontent.com/assets/401965/22270221/ddbf575c-e28e-11e6-8d78-260d9b4a9ec8.png)![default_obsidian_glass](https://cloud.githubusercontent.com/assets/401965/22270220/ddbce90e-e28e-11e6-9c90-9ce269a1faf8.png)![default_obsidian_glass_detail](https://cloud.githubusercontent.com/assets/401965/22270222/ddc3b1a8-e28e-11e6-84dd-eb115688a11a.png)![default_obsidian_shard](https://cloud.githubusercontent.com/assets/401965/22270223/ddc489f2-e28e-11e6-85e9-cabf2433751c.png)![doors_door_obsidian_glass](https://cloud.githubusercontent.com/assets/401965/22270224/ddd06358-e28e-11e6-8cfa-871011cdf234.png)![doors_item_obsidian_glass](https://cloud.githubusercontent.com/assets/401965/22270225/ddd9dd52-e28e-11e6-92c4-7b7a0507fa9e.png)

done
