### ISSUE TITLE
Mithril, Tin & wood amor

### ISSUE THREAD

**Issue by lightonflux** [SummerFields/Minetest#6]
On servers like Liberty Lands and Games like Carbone there is more amor than SF currently supports. 

E.g. Wood amor, tin amor and mitril amor. 

Is there a possibility that SummerFields supports them?

**Comment by lipki** [comment]
I look what I can do.

**Comment by lipki** [comment]
In the '3d armor mod' that I found, no 'armor tin', but an 'armor admin' and armor ... cactus (seriously !)

**Comment by lightonflux** [comment]
I really don't know why there is cactus either. :) If there was damage on contact that would be awesome but without that… Maybe it is more of a cameo armor like gold is more King then regular armor?!

Tin: LOTT has tin armor:

https://github.com/minetest-LOTT/Lord-of-the-Test/tree/master/mods/lottarmor/textures

**Comment by lipki** [comment]
I made armor.
But LOTT me nightmares.
It's too much work for the moment.

**Comment by lightonflux** [comment]
Thanks again!

No problem LOTT is still far from stable so it might change anyway. 

I think you have to push the changes to github. I can't find the mithril armor here.

**Comment by lipki** [comment]
exact :)
done.
