### ISSUE TITLE
flint

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#60]
![fire_flint_steel](https://cloud.githubusercontent.com/assets/401965/20411643/ae2acbbc-ad22-11e6-851a-7b7ef37a3be5.png)![default_flint](https://cloud.githubusercontent.com/assets/401965/20409836/3195830a-ad1b-11e6-879e-000d4e3be7b0.png)

**Comment by lipki** [comment]
![fire_flint_steel](https://cloud.githubusercontent.com/assets/401965/20413086/315c7762-ad2b-11e6-97e2-07d955a3aa61.png)
![default_flint](https://cloud.githubusercontent.com/assets/401965/20413105/4b811382-ad2b-11e6-8d14-fdc7532b108e.png)

**Comment by tobyplowy** [comment]
@lipki done?
