### ISSUE TITLE
divers

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#61]
![bubble](https://cloud.githubusercontent.com/assets/401965/20409779/307b533c-ad1b-11e6-8c32-43d93c26696c.png)
![crack_anylength](https://cloud.githubusercontent.com/assets/401965/20409781/30826744-ad1b-11e6-9788-42759d758fa0.png)
![default_cloud](https://cloud.githubusercontent.com/assets/401965/20409808/310430b2-ad1b-11e6-9d96-f84712113456.png)
![default_footprint](https://cloud.githubusercontent.com/assets/401965/20409837/319698f8-ad1b-11e6-908d-3936961e3de0.png)
![heart](https://cloud.githubusercontent.com/assets/401965/20409964/33ce4026-ad1b-11e6-8668-abf0c5470be3.png)
![screwdriver](https://cloud.githubusercontent.com/assets/401965/20411704/ed6f554a-ad22-11e6-8deb-ec920662db4b.png)

**Comment by lipki** [comment]
![bubble](https://cloud.githubusercontent.com/assets/401965/20413056/f5da72ca-ad2a-11e6-9cf5-5f363984c78e.png)
![crack_anylength](https://cloud.githubusercontent.com/assets/401965/20413057/f7f856d0-ad2a-11e6-9bca-7180dbf86076.png)
![default_cloud](https://cloud.githubusercontent.com/assets/401965/20413059/fd038000-ad2a-11e6-9708-91afa1d41a4c.png)
![heart](https://cloud.githubusercontent.com/assets/401965/20413072/15e919f4-ad2b-11e6-9c6e-f2036718b161.png)
![screwdriver](https://cloud.githubusercontent.com/assets/401965/20413073/17bfa324-ad2b-11e6-90d0-778f849c0807.png)

**Comment by tobyplowy** [comment]
This is done

**Comment by tobyplowy** [comment]
@lipki is this done?

**Comment by lipki** [comment]
The clouds are not good.

**Comment by tobyplowy** [comment]
@lipki I don't think you can edit the clouds
