### ISSUE TITLE
iron

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#62]
![default_mineral_iron](https://cloud.githubusercontent.com/assets/401965/20409881/3269834e-ad1b-11e6-9c5a-ab63b29550ca.png)![default_iron_lump](https://cloud.githubusercontent.com/assets/401965/20409859/31ff7ac6-ad1b-11e6-8b19-428abedf860f.png)

**Comment by lipki** [comment]
![default_mineral_iron](https://cloud.githubusercontent.com/assets/401965/20414569/5eb486d4-ad33-11e6-9216-6b42fd06a8c0.png)![default_iron_lump](https://cloud.githubusercontent.com/assets/401965/20414570/613a8098-ad33-11e6-931d-60da27ad746e.png)

**Comment by tobyplowy** [comment]
@lipki ca you use this 
![iron_nugget](https://cloud.githubusercontent.com/assets/16853304/21283431/720ef954-c402-11e6-897b-18c2ecc977e4.png)
 as default_iron_lump.png

**Comment by lipki** [comment]
Is not exactly the same thing.

nuggets : ![image jpeg 600 x 302 pixels](https://cloud.githubusercontent.com/assets/401965/21288013/79e12082-c478-11e6-90d7-a25d9c015738.jpeg)
lump : ![image jpeg 1024 x 721 pixels](https://cloud.githubusercontent.com/assets/401965/21288015/811209a2-c478-11e6-85d0-219b0fc25910.jpeg)

**Comment by tobyplowy** [comment]
@lipki oh ok btw I Almost have Time Again for Summerfields

**Comment by lipki** [comment]
![default_mineral_iron](https://cloud.githubusercontent.com/assets/401965/22266375/09ad14d0-e280-11e6-9554-d7ffc1cb34ef.png)
