### ISSUE TITLE
moreores mithril tool

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#64]

**Comment by lipki** [comment]
![moreores_tool_mithrilaxe](https://cloud.githubusercontent.com/assets/401965/20414812/bdae18d4-ad34-11e6-9b59-14c00a160333.png)![moreores_tool_mithrilhoe](https://cloud.githubusercontent.com/assets/401965/20414813/bdd78d72-ad34-11e6-8617-4080450f690a.png)![moreores_tool_mithrilpick](https://cloud.githubusercontent.com/assets/401965/20414814/bdd7eb1e-ad34-11e6-9b77-2fb2adaf76a1.png)![moreores_tool_mithrilshovel](https://cloud.githubusercontent.com/assets/401965/20414816/bde13872-ad34-11e6-8d27-e81a969548a5.png)![moreores_tool_mithrilsword](https://cloud.githubusercontent.com/assets/401965/20414815/bddf084a-ad34-11e6-9eac-80b01e0b1442.png)

**Comment by tobyplowy** [comment]
@lipki These tools look super cool

It only needs a new ore and than this is also done

**Comment by lipki** [comment]
redirect #89
