### ISSUE TITLE
tin

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#67]

**Comment by lipki** [comment]
![moreores_mineral_tin](https://cloud.githubusercontent.com/assets/401965/20449783/ceb3c7a2-adeb-11e6-9237-65260220b493.png)![moreores_tin_block](https://cloud.githubusercontent.com/assets/401965/20449784/cedaf21e-adeb-11e6-9abf-2e5a92c23d55.png)![moreores_tin_ingot](https://cloud.githubusercontent.com/assets/401965/20449785/cede2132-adeb-11e6-8027-d2254e2f09d0.png)![moreores_tin_lump](https://cloud.githubusercontent.com/assets/401965/20449786/d0684a6e-adeb-11e6-83b4-32387ccfd8f6.png)

**Comment by tobyplowy** [comment]
@lipki it needs a new ore and then it's done

**Comment by lipki** [comment]
I wait to retest Moreores

**Comment by lipki** [comment]
redirect #89
