### ISSUE TITLE
quartz

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#68]

**Comment by lipki** [comment]
![quartz_block](https://cloud.githubusercontent.com/assets/401965/20449832/253057bc-adec-11e6-8b33-cecf86a63158.png)![quartz_chiseled](https://cloud.githubusercontent.com/assets/401965/20449834/255ac588-adec-11e6-86f3-bf1c7ab356b0.png)![quartz_crystal_full](https://cloud.githubusercontent.com/assets/401965/20449836/255ed15a-adec-11e6-86c4-bb3a533c7fd9.png)![quartz_crystal_piece](https://cloud.githubusercontent.com/assets/401965/20449835/255ebde6-adec-11e6-843e-a6eb8ebb74ce.png)![quartz_ore](https://cloud.githubusercontent.com/assets/401965/20449837/256183a0-adec-11e6-8988-28b020b879ee.png)![quartz_pillar_side](https://cloud.githubusercontent.com/assets/401965/20449838/2566dcc4-adec-11e6-93bb-07a7a3bb4fe5.png)![quartz_pillar_side_horizontal](https://cloud.githubusercontent.com/assets/401965/20449833/254e9e48-adec-11e6-9f4b-e1df99986c32.png)![quartz_pillar_top](https://cloud.githubusercontent.com/assets/401965/20449839/256c7454-adec-11e6-80c1-3b2009543876.png)

**Comment by tobyplowy** [comment]
@lipki This is done yes?

**Comment by lipki** [comment]
![quartz_polishquartz_bottom](https://cloud.githubusercontent.com/assets/401965/22270080/5830ac94-e28e-11e6-9bb5-31df338a2f9b.png)![quartz_polishquartz_side](https://cloud.githubusercontent.com/assets/401965/22270081/58321a02-e28e-11e6-9603-052db648646a.png)![quartz_quartzblock](https://cloud.githubusercontent.com/assets/401965/22270083/5838139e-e28e-11e6-8afb-748a6b975210.png)![quartz_quartzbrick_bottom](https://cloud.githubusercontent.com/assets/401965/22270082/58377812-e28e-11e6-8f3d-934d0565729b.png)![quartz_quartzbrick_side](https://cloud.githubusercontent.com/assets/401965/22270084/583c5986-e28e-11e6-9417-c03ac32dce76.png)![quartz_quartz_fragment](https://cloud.githubusercontent.com/assets/401965/22270085/5840f8e2-e28e-11e6-8aa6-0058798e0d5c.png)![quartz_quartz_ore](https://cloud.githubusercontent.com/assets/401965/22270086/58504b1c-e28e-11e6-85e4-59211fecdd62.png)

https://forum.minetest.net/viewtopic.php?f=9&t=16426&hilit=quartz
