### ISSUE TITLE
Powered Rail and Brake Rail

### ISSUE THREAD

**Issue by lightonflux** [SummerFields/Minetest#7]
I just realized that the brake and power rail are not supported by this texture pack. Which looks rather disturbing from a rail safety perspective. It is a miracle that the carts do not derail. :)

 
![auswahl_064](https://cloud.githubusercontent.com/assets/1377943/6266386/60920fb2-b839-11e4-9268-100d67b972f6.png)

**Comment by lipki** [comment]
:D 
What mod?

**Comment by lightonflux** [comment]
carts, carts-plus and boost_cart all have them. 

https://github.com/SmallJoker/boost_cart/tree/master/textures
https://github.com/PilzAdam/carts/tree/master/textures
https://github.com/Kilarin/minetest-mod-carts-plus/tree/master/textures

**Comment by lipki** [comment]
Done.
I do not know what use a rail "tour".
So the texture does not necessarily match.

Thank you for your help.

https://summerfields.github.io/official/download.html#form_Minetest
