### ISSUE TITLE
nether

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#70]

**Comment by lipki** [comment]
![nether_brick](https://cloud.githubusercontent.com/assets/401965/20449932/b65ab886-adec-11e6-94a8-93faa9d6a05e.png)![nether_glowstone](https://cloud.githubusercontent.com/assets/401965/20449931/b659f4be-adec-11e6-8a2c-19e2a11554f2.png)![nether_particle](https://cloud.githubusercontent.com/assets/401965/20449933/b65fd762-adec-11e6-92a0-2e01ba9c2a6a.png)![nether_rack](https://cloud.githubusercontent.com/assets/401965/20449934/b66308ce-adec-11e6-8ece-2e749701e3ee.png)![nether_sand](https://cloud.githubusercontent.com/assets/401965/20449936/b6682296-adec-11e6-965b-8eb6a29d12f7.png)
![nether_portal](https://cloud.githubusercontent.com/assets/401965/20449935/b66331fa-adec-11e6-8c6d-972cfeb75026.png)

**Comment by tobyplowy** [comment]
@lipki this is done

**Comment by tobyplowy** [comment]
@lipki is this done?

**Comment by lipki** [comment]
I will look for a mod to test.

**Comment by lipki** [comment]
https://forum.minetest.net/viewtopic.php?f=11&t=5790&hilit=nether
