### ISSUE TITLE
coral

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Minetest#76]
coral
default_coral_skeleton
![default_coral_skeleton](https://cloud.githubusercontent.com/assets/16853304/20450092/e72161bc-aded-11e6-92a4-6ddb9ad2e981.png)
default_coral_brown
![default_coral_brown](https://cloud.githubusercontent.com/assets/16853304/20450094/e726a50a-aded-11e6-8fa6-9e2450707193.png)
default_coral_orange
![default_coral_orange](https://cloud.githubusercontent.com/assets/16853304/20450093/e7225428-aded-11e6-94ff-4f6767c9fab5.png)

**Comment by tobyplowy** [comment]
@lipki ping can you do the coral please i downt have enuf skill

**Comment by tobyplowy** [comment]
@lipki its for 0.4.15 its comming soon rummors say it will be out on newyear

**Comment by tobyplowy** [comment]
@lipki are you interested in doing The orange coral (i Can do The recolor for brown)

**Comment by lipki** [comment]
I would like to find it in the game to see what it gives.
Do you know if textures pack can change the models ?

**Comment by tobyplowy** [comment]
@lipki No I don't think texture packs can Change Models for minetest but you can make a mod 

if you break it you get dead coral the wihite block
default_coral_skeleton

**Comment by tobyplowy** [comment]
@lipki also it's not in the world Generation yet You Can only Get it in Creative (on the last unstable build) you can get the unstable here https://github.com/minetest/minetest_game

**Comment by lipki** [comment]
![default_coral_brown](https://cloud.githubusercontent.com/assets/401965/22188051/356399f2-e111-11e6-8614-8babc8eb0c7e.png)![default_coral_orange](https://cloud.githubusercontent.com/assets/401965/22188053/3568e7fe-e111-11e6-88ad-9d2366c0773c.png)![default_coral_skeleton](https://cloud.githubusercontent.com/assets/401965/22188052/3565e626-e111-11e6-9dfb-3e434697bdee.png)
What do you think ?

**Comment by lipki** [comment]
![1corail-cerveau](https://cloud.githubusercontent.com/assets/401965/22188398/04c47114-e115-11e6-91e7-dc22b049fad5.jpg)

**Comment by lipki** [comment]
not sure

**Comment by tobyplowy** [comment]
@lipki I think the red Texture is good but it needs a better recolor and maybe some noise the brown texture seems good
I'm not a fan of the dead coral at least I think thats the dead coral ( I'm referring To the white block that looks like pebbles maybe that can be used as new gravel texture?)

**Comment by tobyplowy** [comment]
@lipki done?

**Comment by tobyplowy** [comment]
@lipki can you update the forum post?

**Comment by lipki** [comment]
after the release
soon

**Comment by lipki** [comment]
We try to do better for that ?

**Comment by tobyplowy** [comment]
@lipki I'm not sure I think the textures are good

**Comment by tobyplowy** [comment]
@lipki but if you think they are not good you can try to improve it I guess

**Comment by lipki** [comment]
At least default_coral_skeleton

**Comment by lipki** [comment]
![default_coral_skeleton](https://cloud.githubusercontent.com/assets/401965/22304426/b13e4cf2-e337-11e6-937f-eac0b7fd1d29.png)![nodeboxtrees_scoral](https://cloud.githubusercontent.com/assets/401965/22304639/89b58cda-e338-11e6-806d-2c18300e5bea.png)
![capture du 2017-01-25 19-52-49](https://cloud.githubusercontent.com/assets/401965/22304635/8372e52a-e338-11e6-8cca-8232ac9d8573.png)

**Comment by tobyplowy** [comment]
@lipki that is nice 

Did you test the newest version of the mod it has some fixes for textures

**Comment by tobyplowy** [comment]
@lipki yay the new pack update is here can you update the forum page and website

**Comment by tobyplowy** [comment]
@lipki also can this be closed?
