### ISSUE TITLE
0.4.15

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#78]
todo

**Comment by tobyplowy** [comment]
0.4.15 is out! http://www.minetest.net

**Comment by tobyplowy** [comment]
@lipki minetest 0.4.15 is out! http://www.minetest.net

**Comment by tobyplowy** [comment]
@lipki minetest 0.4.15 is a nice update

**Comment by tobyplowy** [comment]
@lipki minetest 0.4.15 is out! http://www.minetest.net

**Comment by tobyplowy** [comment]
@lipki when will this pack update (the new minetest update is out)

**Comment by lipki** [comment]
I am looking for a new job not just a job, but a career (I'm not sure of that word, but, training and etc ...). It takes me a while.

**Comment by tobyplowy** [comment]
@lipki are you leaving the Summerfields project :(

**Comment by tobyplowy** [comment]
@lipki I can't do this alone

**Comment by lipki** [comment]
No, no.
It would be necessary for others to make commits, and I can continue to make the releases.

**Comment by tobyplowy** [comment]
@lipki oh ok

**Comment by tobyplowy** [comment]
@lipki can we update for minetest 0.4.15?

**Comment by tobyplowy** [comment]
@lipki hey can you give me permission to be able to push stuff (I would be able to update this pack easily)

**Comment by tobyplowy** [comment]
@lipki i made this pull https://github.com/SummerFields/Minetest/pull/85 as a test

**Comment by tobyplowy** [comment]
@lipki can you also give me permission tho do the same on

https://github.com/SummerFields/Mod-Twilight-Forest
https://github.com/SummerFields/SummerFields
https://github.com/SummerFields/Mod-Mintest-xDecor

**Comment by lipki** [comment]
You are manager for "Mod-Twilight-Forest" and "Mod-Mintest-xDecor" (it lacks an e), but not for Minetest ....
I have forget, I thought I had done.
Anyway it's done, you can do whatever you want.

**Comment by tobyplowy** [comment]
@lipki thanks for trusting me

**Comment by tobyplowy** [comment]
@lipki can you please make textures for https://github.com/SummerFields/Minetest/issues/76 and https://github.com/SummerFields/Minetest/issues/83
