### ISSUE TITLE
0.4.15 - gui

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#79]
by @tobyplowy 
default_book_slot
![default_book_slot](https://cloud.githubusercontent.com/assets/16853304/20041537/fc204d4e-a46a-11e6-82c2-659919efb27e.png)
vessels_glass_bottle_slot
![vessels_glass_bottle_slot](https://cloud.githubusercontent.com/assets/16853304/20041552/433e2764-a46b-11e6-9a5e-00b4fb1e4cc0.png)

**Comment by tobyplowy** [comment]
@lipki this is all the new gui I think

**Comment by lipki** [comment]
![creative_trash_icon](https://cloud.githubusercontent.com/assets/401965/20976741/bbe05502-bca3-11e6-913a-7d269a9b1108.png)

**Comment by tobyplowy** [comment]
@lipki nice!

**Comment by tobyplowy** [comment]
@lipki this is done

**Comment by lipki** [comment]
The color is wrong.
It would be better in white not?
![capture du 2017-01-24 16-32-05](https://cloud.githubusercontent.com/assets/401965/22260895/2af6869a-e26b-11e6-8646-2458b64532b6.png)

**Comment by tobyplowy** [comment]
@lipki yeh maybe

**Comment by lipki** [comment]
Mouais, anyway it's ugly.
Due to the deformation of the pixels.
So ... done

**Comment by tobyplowy** [comment]
Ok
