### ISSUE TITLE
The glass is too clear

### ISSUE THREAD

**Issue by lightonflux** [SummerFields/Minetest#8]
When playing with the orig TP i always though i want 100% clear glass. And SummerFields does it great, the frames are gorgeous and the glass is clear. I really like it. 

Except that with connected glass there is no indication at all that there is something.  Reflections are sadly not possible at the moment. So the other option would be to unclear the glass(es).

Left is the current glass, on the right the glass is filled with #ebfffe which is 5% solid or 95% transparent.

![arbeitsflache 3_0762](https://cloud.githubusercontent.com/assets/1377943/6497475/88554f4e-c2e0-11e4-9fd8-1fe8ef408a59.png)

I am not sure if this is the right colour, i think you have a better hand for colours. 

And i know that there are many glass textures of different kinds and that changing is much work. 

So i don't ask to change it. I just want to mention it so you can think about it if you want.

**Comment by lipki** [comment]
It does not work, transparency is not supported.
Below 50% transparency, nothing.
Above, is opaque.

**Comment by lightonflux** [comment]
Just noticed that homedecor has transparent curtains. I can't see anything [in the code](https://github.com/VanessaE/homedecor_modpack/blob/6f33c9ff0c9e6b452d24ebb9e5403f75b25d2387/homedecor/window_treatments.lua) and the image is just transparent. 

So i think MT now supports opaque textures. 

![transparent curtains](https://i.imgur.com/LTqcKdB.png)

**Comment by lipki** [comment]
ok I'll try

**Comment by lipki** [comment]
Always not :(

I'm on the latest version 0.4.12

Up, with connected textures, it has no texture at the center, it's just a hole.
Down, with unconnected textures,
we see that transparency is replaced with solid color.

![capture du 2015-04-18 02 14 20](https://cloud.githubusercontent.com/assets/401965/7212981/52f1eb06-e571-11e4-9cc2-25959275e323.png)

**Comment by lightonflux** [comment]
I found the problem:

It is a property of the node. So we have to add "use_texture_alpha = true," to glass in the upstream minetest_game.

**Comment by lipki** [comment]
So, I did what?
: D

**Comment by lightonflux** [comment]
You did nothing wrong. 

Someone has to patch all the objects in minetest_game that are glassy by adding the line "use_texture_alpha = true," to the node definitions. 

I might do it in the future.
