### ISSUE TITLE
bushes

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Minetest#80]
this is for 0.4.15

![default_acacia_bush_stem](https://cloud.githubusercontent.com/assets/16853304/20575893/9d73798e-b1bb-11e6-9074-126eb8138a76.png)
![default_bush_stem](https://cloud.githubusercontent.com/assets/16853304/20575892/9d6ee27a-b1bb-11e6-9a3c-2adc32a94cf7.png)

i made this 
![default_acacia_bush_stem](https://cloud.githubusercontent.com/assets/16853304/20575975/0d78bb90-b1bc-11e6-8c22-f2f085ec660f.png)
![default_bush_stem](https://cloud.githubusercontent.com/assets/16853304/20575976/0d91bff0-b1bc-11e6-9950-9c6c3babc9f9.png)
but it needs a recolor and the textures are bad @lipki perhaps you can do better :/

**Comment by tobyplowy** [comment]
@lipki this is also done (you posted the textures in the other issue)

**Comment by lipki** [comment]
Ah! But that's better, I forgot.

**Comment by lipki** [comment]
Yeah, we take that.
![capture du 2017-01-24 21-20-23](https://cloud.githubusercontent.com/assets/401965/22265148/03fe7060-e27b-11e6-9b4b-e05befdcf276.png)
