### ISSUE TITLE
Make items in 47 * 47

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#82]
With the items in 32 * 32 the rendering is the one on the right, if one makes the items in 47 * 47, the rendering is that of the left.

![icone](https://cloud.githubusercontent.com/assets/401965/20644826/3812b316-b445-11e6-9133-d2c2708cddcc.png)

I do not redesign the bucket, so it seems small.
With this system, it will need sometimes completely redesigned the item.

So what do you think?

**Comment by tobyplowy** [comment]
@lipki left looks better but we shuld not fix this the minetest devs shuld to

**Comment by lipki** [comment]
yes, you right
