### ISSUE TITLE
key and bone key

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Minetest#83]
@lipki keys
default_key_skeleton
![default_key_skeleton](https://cloud.githubusercontent.com/assets/16853304/20843576/1d216036-b8bc-11e6-90b6-cd786d55e5b3.png)
default_key
![default_key](https://cloud.githubusercontent.com/assets/16853304/20843577/1d576118-b8bc-11e6-8c8d-9b5421083e56.png)

**Comment by tobyplowy** [comment]
@lipki this is for the next update 0.4.15

**Comment by tobyplowy** [comment]
@lipki can you make textures for this?

**Comment by lipki** [comment]
![default_key_skeleton](https://cloud.githubusercontent.com/assets/401965/22261959/3c45c966-e26f-11e6-9092-5fe85b0f5680.png)![default_key](https://cloud.githubusercontent.com/assets/401965/22261958/3c45c344-e26f-11e6-935c-8d808ba333b4.png)

**Comment by tobyplowy** [comment]
@lipki nice done?

**Comment by lipki** [comment]
yes
