### ISSUE TITLE
nodebox_trees mod support

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Minetest#84]
@lipki you can get it here https://forum.minetest.net/viewtopic.php?f=9&t=16292&sid=1dcb3c4aa2198c978b6724bbecfe67e6

**Comment by tobyplowy** [comment]
what needs to be done 
![nodeboxtrees_acacia_leaves](https://cloud.githubusercontent.com/assets/16853304/21582858/6d48d968-d068-11e6-8689-eeedaefa028c.png)
![nodeboxtrees_acacia_leaves_simple](https://cloud.githubusercontent.com/assets/16853304/21582859/6d4d806c-d068-11e6-9882-f72d3d61ab8f.png)
![nodeboxtrees_aspen_leaves](https://cloud.githubusercontent.com/assets/16853304/21582860/6d4d9d7c-d068-11e6-82fc-68f27a62bebb.png)
![nodeboxtrees_bcoral](https://cloud.githubusercontent.com/assets/16853304/21582863/6d4efd34-d068-11e6-9864-fe0b3e4ad0a9.png)
![nodeboxtrees_cactus](https://cloud.githubusercontent.com/assets/16853304/21582861/6d4ea276-d068-11e6-89d7-d1aafeaec882.png)
![nodeboxtrees_jungleleaves](https://cloud.githubusercontent.com/assets/16853304/21582862/6d4e9498-d068-11e6-85ac-fe52f0902970.png)
![nodeboxtrees_leaves](https://cloud.githubusercontent.com/assets/16853304/21582864/6d5e1b0c-d068-11e6-8a69-22800427bbd2.png)
![nodeboxtrees_leaves_simple](https://cloud.githubusercontent.com/assets/16853304/21582865/6d62918c-d068-11e6-93a7-5a52eca8d1fa.png)
![nodeboxtrees_leaves_snow](https://cloud.githubusercontent.com/assets/16853304/21582866/6d62ed4e-d068-11e6-857b-361a107d2984.png)
![nodeboxtrees_leaves_snow_simple](https://cloud.githubusercontent.com/assets/16853304/21582867/6d637da4-d068-11e6-9b7c-ed6e113759bb.png)
![nodeboxtrees_ocoral](https://cloud.githubusercontent.com/assets/16853304/21582868/6d63da38-d068-11e6-91ec-0d19fa2c278c.png)
![Uploading nodeboxtrees_pine_needles.png…]()
![Uploading nodeboxtrees_pine_needles_snow.png…]()
![Uploading nodeboxtrees_scoral.png…]()
![Uploading nodeboxtrees_waterlily.png…]()
![Uploading nodeboxtrees_waterlily_noflower.png…]()

**Comment by lipki** [comment]
![nodeboxtrees_acacia_leaves](https://cloud.githubusercontent.com/assets/401965/22187654/cbaaa1a0-e10a-11e6-9231-b32523c7efd9.png)
![nodeboxtrees_acacia_leaves_simple](https://cloud.githubusercontent.com/assets/401965/22187653/cba8655c-e10a-11e6-8f85-90b2d8bf0c6f.png)
![nodeboxtrees_aspen_leaves](https://cloud.githubusercontent.com/assets/401965/22187657/cbb2d244-e10a-11e6-81ab-ce6423ccc395.png)
![nodeboxtrees_cactus](https://cloud.githubusercontent.com/assets/401965/22187655/cbafefde-e10a-11e6-96ab-ef129b02b976.png)
![nodeboxtrees_jungleleaves](https://cloud.githubusercontent.com/assets/401965/22187656/cbb0fad2-e10a-11e6-9f73-21ce44e92726.png)
![nodeboxtrees_leaves](https://cloud.githubusercontent.com/assets/401965/22187658/cbb45dda-e10a-11e6-966e-8bf6efb0fa80.png)
![nodeboxtrees_leaves_simple](https://cloud.githubusercontent.com/assets/401965/22187659/cbc3b8c0-e10a-11e6-926b-b10d121427e1.png)
![nodeboxtrees_leaves_snow](https://cloud.githubusercontent.com/assets/401965/22187660/cbc9e9a2-e10a-11e6-94f0-10ac74797ed0.png)
![nodeboxtrees_leaves_snow_simple](https://cloud.githubusercontent.com/assets/401965/22187661/cbccb3f8-e10a-11e6-8147-83d20dfd0181.png)
![nodeboxtrees_pine_needles](https://cloud.githubusercontent.com/assets/401965/22187662/cbcf6c88-e10a-11e6-84b7-955a623080a8.png)
![nodeboxtrees_pine_needles_snow](https://cloud.githubusercontent.com/assets/401965/22187663/cbd3a5b4-e10a-11e6-89dd-4d07c7757e96.png)
![nodeboxtrees_waterlily](https://cloud.githubusercontent.com/assets/401965/22187664/cbd51e76-e10a-11e6-824d-b227ee4fea14.png)
![nodeboxtrees_waterlily_noflower](https://cloud.githubusercontent.com/assets/401965/22187665/cbdf8230-e10a-11e6-83f1-12989966d927.png)

**Comment by tobyplowy** [comment]
@lipki thank you

**Comment by tobyplowy** [comment]
@lipki now just the coral and this is done

**Comment by tobyplowy** [comment]
Can you put it on the mod support list on the forums https://forum.minetest.net/viewtopic.php?f=4&t=9314

**Comment by lipki** [comment]
I work on corals.

**Comment by tobyplowy** [comment]
OK nice

**Comment by tobyplowy** [comment]
@lipki also welcome back I missed you :)

**Comment by lipki** [comment]
![nodeboxtrees_bcoral](https://cloud.githubusercontent.com/assets/401965/22188406/2112d16c-e115-11e6-8873-9c1c222c1a8b.png)![nodeboxtrees_ocoral](https://cloud.githubusercontent.com/assets/401965/22188407/21146892-e115-11e6-9e56-e713439c1fe7.png)![nodeboxtrees_scoral](https://cloud.githubusercontent.com/assets/401965/22188408/21167146-e115-11e6-850c-6b7853079d1e.png)

![1corail-etoile-massif](https://cloud.githubusercontent.com/assets/401965/22188409/272a51a6-e115-11e6-9a44-8ceae14ce53b.jpg)

**Comment by tobyplowy** [comment]
@lipki fix for brown and dead coral
![21167146-e115-11e6-850c-6b7853079d1e](https://cloud.githubusercontent.com/assets/16853304/22199410/0d2023f8-e15b-11e6-8cae-e9547e48d84c.png)
![2112d16c-e115-11e6-8873-9c1c222c1a8b](https://cloud.githubusercontent.com/assets/16853304/22199411/0d217690-e15b-11e6-86df-b94ed5005a0e.png)

**Comment by tobyplowy** [comment]
@lipki also you can get rid of the snow leafs

**Comment by tobyplowy** [comment]
@lipki the mod got an update (and i made it XD)

**Comment by tobyplowy** [comment]
@lipki also if you wanna have a good map to test the textures you can use this
[custom trees gg.zip](https://github.com/SummerFields/Minetest/files/723294/custom.trees.gg.zip)

**Comment by lipki** [comment]
Snow no more use, but I let her.

**Comment by tobyplowy** [comment]
@lipki eeehhhh that was ridiculously hard to understand but ok I do understand it

**Comment by lipki** [comment]
If the feature back, the textures will be there.

**Comment by tobyplowy** [comment]
@lipki that's a good point!
