### ISSUE TITLE
mod Moreores

### ISSUE THREAD

**Issue by lipki** [SummerFields/Minetest#89]
https://forum.minetest.net/viewtopic.php?id=549
![moreores_copper_rail](https://cloud.githubusercontent.com/assets/401965/22300492/f92feabc-e327-11e6-9ec7-2531fe63da50.png)![moreores_copper_rail_crossing](https://cloud.githubusercontent.com/assets/401965/22300494/f95edf48-e327-11e6-9588-6fdae3b41dc5.png)![moreores_copper_rail_curved](https://cloud.githubusercontent.com/assets/401965/22300496/f9610b6a-e327-11e6-9298-9fd02516730e.png)![moreores_copper_rail_t_junction](https://cloud.githubusercontent.com/assets/401965/22300495/f95fa4aa-e327-11e6-9ede-ed878c774d6a.png)
![moreores_mineral_mithril](https://cloud.githubusercontent.com/assets/401965/22300498/f969a6ee-e327-11e6-86ed-e3f383f9aee0.png)![moreores_mineral_silver](https://cloud.githubusercontent.com/assets/401965/22300497/f96897ae-e327-11e6-9bf1-a6bee3e800d3.png)![moreores_mineral_tin](https://cloud.githubusercontent.com/assets/401965/22300493/f94ed31e-e327-11e6-94cc-3aa969123d8f.png)
![moreores_mithril_block](https://cloud.githubusercontent.com/assets/401965/22300499/f96ce318-e327-11e6-80ba-3e09039340b3.png)![moreores_silver_block](https://cloud.githubusercontent.com/assets/401965/22300502/f9865d5c-e327-11e6-97bd-bde316948cd9.png)![moreores_tin_block](https://cloud.githubusercontent.com/assets/401965/22300504/f98ff362-e327-11e6-9b1d-7154aa025d3b.png)
![moreores_mithril_ingot](https://cloud.githubusercontent.com/assets/401965/22300500/f97de3f2-e327-11e6-8d32-5bc58cf104ea.png)![moreores_silver_ingot](https://cloud.githubusercontent.com/assets/401965/22300503/f9888e38-e327-11e6-97fb-8669709a5794.png)![moreores_tin_ingot](https://cloud.githubusercontent.com/assets/401965/22300506/f99f8638-e327-11e6-9524-32cc555f86ea.png)
![moreores_mithril_lump](https://cloud.githubusercontent.com/assets/401965/22300501/f9836714-e327-11e6-9216-5a4be9149ae2.png)![moreores_silver_lump](https://cloud.githubusercontent.com/assets/401965/22300505/f995bf72-e327-11e6-9d09-bedf5a629655.png)![moreores_tin_lump](https://cloud.githubusercontent.com/assets/401965/22300507/f9a23ae0-e327-11e6-8197-1ae04b938347.png)
![moreores_tool_mithrilaxe](https://cloud.githubusercontent.com/assets/401965/22300510/f9b0238a-e327-11e6-904a-8f833fb9d23d.png)![moreores_tool_mithrilhoe](https://cloud.githubusercontent.com/assets/401965/22300508/f9a91fc2-e327-11e6-942e-c283a3441e11.png)![moreores_tool_mithrilpick](https://cloud.githubusercontent.com/assets/401965/22300509/f9af7412-e327-11e6-923f-a03f38262417.png)![moreores_tool_mithrilshovel](https://cloud.githubusercontent.com/assets/401965/22300511/f9b9e104-e327-11e6-9f6f-1e6abb6132dc.png)![moreores_tool_mithrilsword](https://cloud.githubusercontent.com/assets/401965/22300512/f9be78e0-e327-11e6-8ab9-31bf26db8515.png)
![moreores_tool_silveraxe](https://cloud.githubusercontent.com/assets/401965/22300513/f9c3734a-e327-11e6-9607-bf7162e0f18e.png)![moreores_tool_silverhoe](https://cloud.githubusercontent.com/assets/401965/22300514/f9c92efc-e327-11e6-8724-67f30f1d9976.png)![moreores_tool_silverpick](https://cloud.githubusercontent.com/assets/401965/22300515/f9cc9560-e327-11e6-9df4-be3fd1e4f5d4.png)![moreores_tool_silvershovel](https://cloud.githubusercontent.com/assets/401965/22300516/f9ce63fe-e327-11e6-860d-11b968fcdbee.png)![moreores_tool_silversword](https://cloud.githubusercontent.com/assets/401965/22300517/f9daa588-e327-11e6-97d5-c77651aeb548.png)

**Comment by tobyplowy** [comment]
@lipki I think we should update the bace pack before we focus on mods

**Comment by lipki** [comment]
![carts_rail_cp](https://cloud.githubusercontent.com/assets/401965/22303384/5cff6dbe-e333-11e6-9cb5-eecc567d91b2.png)![carts_rail_crossing_cp](https://cloud.githubusercontent.com/assets/401965/22303385/5d016966-e333-11e6-9b06-87d8a3125d75.png)![carts_rail_curved_cp](https://cloud.githubusercontent.com/assets/401965/22303386/5d03ea74-e333-11e6-9571-f3cc24228ee0.png)![carts_rail_t_junction_cp](https://cloud.githubusercontent.com/assets/401965/22303387/5d04b170-e333-11e6-9a41-04c8bb09a71c.png)
![moreores_mithril_block](https://cloud.githubusercontent.com/assets/401965/22303395/67386d08-e333-11e6-8083-bd527f7b2caa.png)![moreores_mithril_ingot](https://cloud.githubusercontent.com/assets/401965/22303410/7af3cd4c-e333-11e6-89f5-b829a643ee8e.png)![moreores_mithril_lump](https://cloud.githubusercontent.com/assets/401965/22303415/7ec0d708-e333-11e6-944d-fab580cf987d.png)![ore_lead](https://cloud.githubusercontent.com/assets/401965/22303586/378745c4-e334-11e6-90e5-921f4439431e.png)![moreores_tool_mithrilaxe](https://cloud.githubusercontent.com/assets/401965/22303425/8a3b492e-e333-11e6-882f-5eaca92b684b.png)![moreores_tool_mithrilhoe](https://cloud.githubusercontent.com/assets/401965/22303426/8a3d1894-e333-11e6-91b5-2b959c4f6e6f.png)![moreores_tool_mithrilpick](https://cloud.githubusercontent.com/assets/401965/22303428/8a4216d2-e333-11e6-9823-6e072831be3f.png)![moreores_tool_mithrilshovel](https://cloud.githubusercontent.com/assets/401965/22303427/8a41626e-e333-11e6-89cc-d76edb82fc12.png)![moreores_tool_mithrilsword](https://cloud.githubusercontent.com/assets/401965/22303429/8a4354e8-e333-11e6-926d-fa0703ad8de6.png)
![moreores_silver_block](https://cloud.githubusercontent.com/assets/401965/22303396/6946c7a2-e333-11e6-9483-c6ef756d4f03.png)![moreores_silver_ingot](https://cloud.githubusercontent.com/assets/401965/22303453/9af6f150-e333-11e6-9b90-2f689d73beac.png)![moreores_silver_lump](https://cloud.githubusercontent.com/assets/401965/22303458/9d6014ee-e333-11e6-86a3-8eb180c6d926.png)![ore_silver](https://cloud.githubusercontent.com/assets/401965/22303515/e4eea938-e333-11e6-9a13-f6033c77a902.png)![moreores_tool_silveraxe](https://cloud.githubusercontent.com/assets/401965/22303461/a1607df4-e333-11e6-9dbc-7f868ed6a051.png)![moreores_tool_silverhoe](https://cloud.githubusercontent.com/assets/401965/22303462/a1659776-e333-11e6-9010-9c8e8ff29d0a.png)![moreores_tool_silverpick](https://cloud.githubusercontent.com/assets/401965/22303463/a168cf04-e333-11e6-90ea-757dfcf6d3fd.png)![moreores_tool_silvershovel](https://cloud.githubusercontent.com/assets/401965/22303464/a16f1cd8-e333-11e6-9e45-e04c1413b6f1.png)![moreores_tool_silversword](https://cloud.githubusercontent.com/assets/401965/22303465/a1814174-e333-11e6-95ac-43be33b7eeae.png)
![moreores_tin_block](https://cloud.githubusercontent.com/assets/401965/22303397/6a71a4bc-e333-11e6-830f-d9ee014ee0c5.png)![moreores_tin_ingot](https://cloud.githubusercontent.com/assets/401965/22303479/ae631764-e333-11e6-8d7c-e6b10427738e.png)![moreores_tin_lump](https://cloud.githubusercontent.com/assets/401965/22303480/b03ba5ec-e333-11e6-946e-23cd675b3909.png)![ore_tin](https://cloud.githubusercontent.com/assets/401965/22303535/faa7a572-e333-11e6-9551-e9452468c30b.png)

**Comment by lipki** [comment]
We have all the textures, so I put them in.

**Comment by lipki** [comment]
![moreores_mineral_mithril](https://cloud.githubusercontent.com/assets/401965/22304016/0cb3e5ee-e336-11e6-89a2-09f6ba55002c.png)
![moreores_mineral_silver](https://cloud.githubusercontent.com/assets/401965/22304017/0cb85bc4-e336-11e6-99eb-ae8adc4a0d9b.png)
![moreores_mineral_tin](https://cloud.githubusercontent.com/assets/401965/22304018/0cba2c10-e336-11e6-9c05-fcc723c777d2.png)
